# 是否打印进度 
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 30
  # 检查间隔,单位分钟
  interval: 10
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 9216
  # 下载测试超时时间 单位秒
  download-timeout: 5
  # 测速下载大小 单位MB
  download-size: 50
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 2
  # 测速数量
  speed-count: 13
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  # 临时节点
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - https://yefengjc.xyz/api/yefeng?token=b6bad09ea5d97ded07c0bf9219e02359&flag=meta
  - https://xn--9kqx21a0sv.com/api/bpyun?token=7a3de00993e5401dd1ae6b137216550b
  - http://xm.1iun.com/api/v1/client/subscribe?token=c05745bfd4663dd8f9029491980ec8b6
  - https://submit.xz61.cn:23443/api/v1/client/subscribe?token=696d0b1f92df46059f9c923cf5320232
  - https://tt.vg/OrddG
  - https://bh.jiedianxielou.workers.dev/
  - https://211.threebrother.top/sub/b46e2363-c46b-4b98-b3d6-898de56d039c.html
  - https://bayoeorescentpossessicoanseparateuneforescenphocommitte.adoptangelaboradvacotionclwonthorughconfrmcompimentdeseertaltar.org/link/PkHuTjYpRZGnaxwE?clash=1
  - https://bayoeorescentpossessicoanseparateuneforescenphocommitte.adoptangelaboradvacotionclwonthorughconfrmcompimentdeseertaltar.org/link/lH7DxnPZQOom6hq2?clash=1
  - https://bayoeorescentpossessicoanseparateuneforescenphocommitte.adoptangelaboradvacotionclwonthorughconfrmcompimentdeseertaltar.org/link/JxkxKsnVfueVdKeb?clash=1
  - http://vless.809098.xyz/
  - https://igdux.top/CKnRRPmmX54fCcachC5aaQ2h
  - https://x.juzi.lat/view.php?id=4f791577a9bfaaf8
  - https://nano.nachoneko.cn/api/v1/client/subscribe?token=15c8b2771610ae4fe00282f1035a44d9
  - https://666676666.xyz/api/v1/client/subscribe?token=f701ce71294b488eebc00937d841bebb
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA
  - https://n063ww4.wxll4.cfd/api/v1/client/subscribe?token=676782dc6736a2f0d89f4f42b7e884e8
  - https://sub.miaolianyun.vip/mly_sub?token=17798f36a432a1ccaeb6ea0744cfd10b
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA
  - https://www.tiziwrops.com/api/v1/client/subscribe?token=8fa788726eb4b5323e2d19297d5147e1
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA#%E6%98%9F%E9%93%BEStarlink%20%E2%9C%A8
  - https://6bsub.zhunchuanpb.com/api/v1/client/subscribe?token=9073771badd26857dd11f3d1bc15803f
  - https://1.bethebest.eu.org/api/v1/client/subscribe?token=846d0801c50b4d5bc700617a1e38caaf
  - https://666676666.xyz/api/v1/client/subscribe?token=dc8260cdabfb187bf48f5963ea032678
  - https://nxsubnx.hhkkdd.cn/api/v1/client/subscribe?token=e46318fcbfbecc08e348004fb051b4ba
  - http://8.129.23.122/s/5fc9a1457054d335feb23235bd8b9225
  - https://link.onesy.link/link/kMkHYontpUfl7S06?clash=1
  - https://www.flyintpro05.com/api/v1/client/subscribe?token=62be89e4bc828cdfd0c62bfb44746312
  - https://rgergergergerg6555.saojc.xyz/api/v1/client/subscribe?token=a29191a8042e2e2fb1f3a93d0f27c5b1
  - https://api.sraylink.com/api/client/?token=ff19aac0ee34ed7050411caf5f0c8538
  - https://rigengjiedian.one/api/system/subscribe
  - https://igdux.top/sNA4nHY75fiXA2jFCDd76a5d
  - https://igdux.top/AzJFReQ3nPNR5yYfXXrQ6rcx
  - https://book.hostnow.top/api/v1/client/subscribe?token=e1a90ec2dfd92a6a8f75b3b224ecfbaa
  - https://igdux.top/TwcchR34f7dGeH4Hza6nyfWF
  - https://sub.verybigball.org/download-sub/?sid=151788&uid=3760&token=64e0e48a77343e4971fb&app=auto
  # 总节点保存
  - https://raw.githubusercontent.com/mitjavaz/memo/master/allNodes.yaml
  - https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub4.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub5.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub6.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub7.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub8.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub9.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub10.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vmess.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vless.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/trojan.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ss.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ssr.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/tuic.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/hysteria2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Warp_sub.txt
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  # TG #
  # 蛋黄酱节点分享：@FProxies
    # 0404节点
  - https://sub.danhu.ddns-ip.net/paste/jGd0KIXz3l5XmaLW/urls
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  - https://svip.xy666.ggff.net/auto
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/