# 是否打印进度 
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 120
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://www.youtube.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 9999
  # 下载测试超时时间 单位秒
  download-timeout: 5
  # 测速下载大小 单位MB
  download-size: 50
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 2
  # 测速数量
  speed-count: 16
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  # 临时节点
  - 
  - 
  - 
  - 
  - 
  - 
  - http://sub2.127665.xyz/s/37442697d1092ed5ececa7609f851afe
  - https://banyunxiaoxi.icu/2025/05/22/2025-05-22%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0106%E4%B8%AA/
  - https://ktmcloud.net/api/v1/client/subscribe?token=8a84fc496705d0671ef40aeb0f9ff97e
  - https://v1.mk/LynJ4qQ
  - https://abjc.xyz/api/abjc?token=455ae217f6041f9fae9afb50531a53a5
  - https://abjc.xyz/api/abjc?token=289e83192d8ce1d90f84a6074be3b75a
  - https://abjc.xyz/api/abjc?token=61edff571c8569e11d4d78e852c3658a
  - https://abjc.xyz/api/abjc?token=dae057133e4e3c4859560bee100c015c
  - https://abjc.xyz/api/abjc?token=4fd01dc4ff66e4ea0662beeab533f519
  - https://abjc.xyz/api/abjc?token=381ae744d4c6fd17cc633e424ac6f938
  - https://abjc.xyz/api/abjc?token=0d514085f49b95a435b81b7c21eb1b85
  - https://abjc.xyz/api/abjc?token=819d34229f745a02bfad3761e3be8a3a
  - https://abjc.xyz/api/abjc?token=f10e2042f0de04e65f2df05f2e1916b1
  - https://www8.bigairport-eleventh-sub.com/api/v1/client/subscribe?token=3ef89b44f3d6708eb3f0c125270ba55d
  - https://app.mitce.net/?sid=229127&token=195c2ddf052d86180283
  - https://fb.xz61.cn/api/v1/client/subscribe?token=544ac0d96a109a26b9bf0c18f23e6b85
  - https://sub.miaopu.cf/lsub/E3JG4k50xoAx8BiS?sub=3&extend=1
  - https://sub.miaopu.cf/lsub/SWl6knyYIxEPTLmH?clash=1&extend=1
  - https://app.mitce.net/?sid=229127&token=195c2ddf052d86180283
  - https://fb.xz61.cn/api/v1/client/subscribe?token=544ac0d96a109a26b9bf0c18f23e6b85#%23%23%23%23/%E4%BD%BF%E5%8A%B2%E5%88%B7
  - https://banyunxiaoxi.icu/2025/05/21/2025-05-21%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0134%E4%B8%AA/
  - https://igdux.top/jXyGGWkjTYdzF2GTNfazekDB
  - https://banyunxiaoxi.icu/2025/05/19/2025-05-19%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0119%E4%B8%AA/
  - https://d1.mk/xPv6wHv
  - https://v1.mk/ndLrlHV
  - https://xn--mesz9ptugxg.com/api/v1/client/subscribe?token=dcb2eb6379a152bbe397572220e8e4a8
  - https://fao9itw.nicecloud.win:8443/api/v1/client/e7fb973a717a1fc9f240075674986515
  - https://abjc.xyz/api/abjc?token=61cfbe1fe61ff66412fa17d3691622d3
  - https://ylks.tt2000.sbs/2025/F4/u16/c.yaml
  - https://abjc.xyz/api/abjc?token=61cfbe1fe61ff66412fa17d3691622d3
  - https://sub.tsjc.shop/api/t/e147f5c6a6f0acb7419a688ac99fc73d
  - https://banyunxiaoxi.icu/2025/05/15/2025-05-15%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0109%E4%B8%AA/
  - https://app.mitce.net/?sid=258462&token=srveagks
  - https://app.mitce.net/?sid=258462&token=srveagks
  - https://i.ilikeu.dpdns.org/sub?uuid=865c8324-bd6d-4b87-a9ad-26aa5baf6b1b&encryption=none&security=tls&sni=a.ilikeu.dpdns.org&type=ws&host=a.ilikeu.dpdns.org&path=%2F
  - https://i.ilikeu.dpdns.org/sub?uuid=249c8d42-9111-40a2-a4f6-0add3ebecc3b&encryption=none&security=tls&sni=fl.ilikeu.dpdns.org&alpn=h2%2Chttp%2F1.1&allowInsecure=1&type=ws&host=fl.ilikeu.dpdns.org&path=%2F
  - https://tc.qy1357.top/api/v1/client/subscribe?token=ca3978edf37213745432a0ac538275ca
  - https://banyunxiaoxi.icu/2025/05/14/2025-05-14%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0119%E4%B8%AA/
  - https://ylks.tt2000.sbs/2025/F4/v13/c.yaml
  - https://1.kongcheng777.dpdns.org/sub?token=7e252e1171ecf2581ce17d66df828d13
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1&flag=clash
  - https://x2.xueshan.shop/s/492ad1fe90cd6385109abee093eaf241
  - https://sub.miaopu.cf/lsub/WDw7oG32PncKA9AZ?list=clash
  - https://sub.miaopu.cf/lsub/E3JG4k50xoAx8BiS?sub=3&extend=1
  - https://sub.xn--9kqp0yy4f.com/s/a850a6537d8e8aaa3dbd2e9f47f7d70a
  - https://sub.xn--9kqp0yy4f.com/s/9589adfbccf063beebd2f89e0873c547
  - https://sub.xn--9kqp0yy4f.com/s/bdcb129df2453532343e1eb442af915d
  - https://sub.xn--9kqp0yy4f.com/s/a486e88cea6c0ee7ee2640cd65ca1e8f
  - https://wanmeiwl2.xyz/gywl/3536585b5623f82f3ab9ebef3e32dfe9
  - https://v1.mk/36MAiaU
  - https://abjc.xyz/api/abjc?token=61cfbe1fe61ff66412fa17d3691622d3
  - https://sub.miaopu.cf/lsub/E3JG4k50xoAx8BiS?sub=3&extend=1
  - https://i.ilikeu.dpdns.org/sub?uuid=838f5273-5d2d-4630-a0f5-9cc8e4aef4d6&type=ws&encryption=none&flow=&host=kg.ilikeu.dpdns.org&path=%2F&security=tls&sni=kg.ilikeu.dpdns.org&fp=chrome&packetEncoding=xudp
  - https://i.ilikeu.dpdns.org/sub?uuid=0498252a-77a9-4038-bec9-c066a404de7c&encryption=none&security=tls&sni=claw.orangelightyo.dpdns.org&type=ws&host=claw.orangelightyo.dpdns.org&path=%2F
  - https://i.ilikeu.dpdns.org/sub?uuid=865c8324-bd6d-4b87-a9ad-26aa5baf6b1b&encryption=none&security=tls&sni=a.ilikeu.dpdns.org&type=ws&host=a.ilikeu.dpdns.org&path=%2F
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1&flag=clash
  - https://www.dabai.in/link/Sj23ckEbMJonZB9C?clash=1
  - https://qishuijc.top/api/v1/client/subscribe?token=391afb46752d77774f9848f1b0e30b14
  - https://qishuijc.top/api/v1/client/subscribe?token=6fea2eb70062b0d3970bc3020d2b252b
  - https://www.dabai.in/link/Sj23ckEbMJonZB9C?clash=1
  - https://ylks.tt2000.sbs/2025/F4/z10/c.yaml
  - https://multikeys.outlinekeys.net/Sub/b29rMTEsMTc0NjYwMzA0Nw5jtsaIMXsa
  - https://v1.mk/rETkDGX
  - https://v1.mk/pzO2Rgj
  - https://ylks.tt2000.sbs/2025/F4/z8/c.yaml
  - https://www.roc-taiwan.taipei/link/6vY3rvkzoG0S5jAU?clash=1
  - https://qishuijc.top/api/v1/client/subscribe?token=cc53778b817939d8fd581cc1ed943abc
  - https://qishuijc.top/api/v1/client/subscribe?token=732e0bf0dea00ad0228ec3e01ee15689
  - https://qishuijc.top/api/v1/client/subscribe?token=732e0bf0dea00ad0228ec3e01ee15689
  - https://qishuijc.top/api/v1/client/subscribe?token=cc53778b817939d8fd581cc1ed943abc
  - https://qishuijc.top/api/v1/client/subscribe?token=dfdf7bd5d413a113a9aef80e3de800db
  - https://v1.mk/1rathw1
  - https://v1.mk/AzqTJ7K
  - https://v1.mk/1bvCAWZ
  - https://v1.mk/oFqp5Av
  - https://v1.mk/wpnt2BR
  - https://v1.mk/EGNPuJu
  - https://v1.mk/QQGLm5q
  - https://submit.xz61.cn:23443/api/v1/client/subscribe?token=696d0b1f92df46059f9c923cf5320232
  - https://tt.vg/OrddG
  - https://bh.jiedianxielou.workers.dev/
  - https://igdux.top/CKnRRPmmX54fCcachC5aaQ2h
  - https://nano.nachoneko.cn/api/v1/client/subscribe?token=15c8b2771610ae4fe00282f1035a44d9
  - https://666676666.xyz/api/v1/client/subscribe?token=f701ce71294b488eebc00937d841bebb
  - https://n063ww4.wxll4.cfd/api/v1/client/subscribe?token=676782dc6736a2f0d89f4f42b7e884e8
  - https://sub.miaolianyun.vip/mly_sub?token=17798f36a432a1ccaeb6ea0744cfd10b
  - https://www.tiziwrops.com/api/v1/client/subscribe?token=8fa788726eb4b5323e2d19297d5147e1
  - https://666676666.xyz/api/v1/client/subscribe?token=dc8260cdabfb187bf48f5963ea032678
  - https://nxsubnx.hhkkdd.cn/api/v1/client/subscribe?token=e46318fcbfbecc08e348004fb051b4ba
  - https://www.flyintpro05.com/api/v1/client/subscribe?token=62be89e4bc828cdfd0c62bfb44746312
  - https://rgergergergerg6555.saojc.xyz/api/v1/client/subscribe?token=a29191a8042e2e2fb1f3a93d0f27c5b1
  - https://api.sraylink.com/api/client/?token=ff19aac0ee34ed7050411caf5f0c8538
  - https://rigengjiedian.one/api/system/subscribe
  - https://igdux.top/sNA4nHY75fiXA2jFCDd76a5d
  - https://igdux.top/AzJFReQ3nPNR5yYfXXrQ6rcx
  - https://book.hostnow.top/api/v1/client/subscribe?token=e1a90ec2dfd92a6a8f75b3b224ecfbaa
  - https://igdux.top/TwcchR34f7dGeH4Hza6nyfWF
  # 总节点保存
  - https://raw.githubusercontent.com/mitjavaz/memo/master/allNodes.yaml
  - https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub4.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub5.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub6.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub7.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub8.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub9.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub10.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vmess.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vless.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/trojan.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ss.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ssr.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/tuic.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/hysteria2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Warp_sub.txt
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  # TG #
  # 蛋黄酱节点分享：@FProxies
    # 0404节点
  - https://sub.danhu.ddns-ip.net/paste/0aLyIfZNNKGnpKW9/urls
  - https://sub.danhu.ddns-ip.net/paste/jGd0KIXz3l5XmaLW/urls
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  - https://svip.xy666.ggff.net/auto
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/