# 是否打印进度 
print-progress: true

# 可选值 debug info warn error
log-level: info

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 32
  # 检查间隔,单位分钟
  interval: 10
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 1024
  # 下载测试超时时间 单位秒
  download-timeout: 5
  # 测速下载大小 单位MB
  download-size: 10
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 5
  # 测速数量
  speed-count: 5
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    # openai
    - youtube
    # netflix
    # disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 3
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  # 总节点保存
  - https://raw.githubusercontent.com/mitjavaz/memo/master/allNodes.yaml
  - https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  - https://raw.githubusercontent.com/mitjavaz/memo/master/clash.yaml
  # Github共享节点
  - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  # TG #
  # 蛋黄酱节点分享：@FProxies
    # 0208节点
  - https://sub.danhu.ddns-ip.net/paste/OmJ9zWdyc6ZN9aAe/clash
    # 0308节点
  - https://sub.danhu.ddns-ip.net/paste/zrGnix8y5gf3hv6z/clash
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  # 白嫖のHome：@ZDYZ2
  - https://sublink.634676.xyz/sub
  # 未知名零散节点
  - https://yun-api.subcloud.xyz/sub?target=clash&url=ss%3A%2F%2FY2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTo4ZmJlM3JKVGt5d1l2Ymsz%40cn-gz.k5nf3a.ccddn4.icu%3A25437%23Akari%2520HongKong%2520_%253C%7Cvmess%3A%2F%2FeyJhZGQiOiI1ODE2MTAuZXZlbGluZS5sb2wiLCJhaWQiOiIwIiwiYWxwbiI6IiIsImZwIjoiIiwiaG9zdCI6IiIsImlkIjoiODE3NzVEQzktQjg1MS00QzJBLTNERDMtRTJFMDkwM0FFMkFEIiwibmV0IjoidGNwIiwicGF0aCI6IiIsInBvcnQiOiIzMTEwNCIsInBzIjoiTFNISVkgSG9uZ0tvbmcgX1x1MDAzYyIsInNjeSI6ImF1dG8iLCJzbmkiOiIiLCJ0bHMiOiIiLCJ0eXBlIjoiIiwidiI6IjIifQ%3D%3D%7Css%3A%2F%2FYWVzLTEyOC1nY206YTFkN2FlZWEtNzlmYi00YmZmLThiN2ItZmU1MWVlOGViY2Rl%40south.sf0jm.xyz%3A44406%23Akamai%2520Singapore%2520_%253C&insert=false
  - https://yun-api.subcloud.xyz/sub?target=clash&url=trojan%3A%2F%2F789fa9d6-727e-424d-bdf6-8077d72aa5e2%40hkjs.lydurlclub.top%3A443%2F%3Ftype%3Dtcp%26security%3Dtls%23HKG%252003%2520_%253C%7Ctrojan%3A%2F%2F789fa9d6-727e-424d-bdf6-8077d72aa5e2%40usa.lydurlclub.top%3A443%2F%3Ftype%3Dtcp%26security%3Dtls%23USA%252002%2520_%253C&insert=false
  - https://igdux.top/kfjCFnWmbbMNSmk4j2nJsfYb
  - https://igdux.top/XanKQpzTW45sGNEZZTPpzQ6Q
  - https://cf-workers-sub-9s8.pages.dev/CSDN
  - https://emm-7zy.pages.dev/CSDN
  - https://proxypool.aloes.workers.dev/
  - https://xn--4oq11ryli3rg.com/s/1bc7228f5bc3b955260c2879bb80b509
  - https://xn--4oq11ryli3rg.com/s/26ad946d20f630ddf84a75629a436f1d
  - https://paste.gg/p/ruanianku/1080288024334b468d653ba5f9d7a59d/files/867170480c5944b9946dc2e86e7de039/raw
  - https://b7af2e827532cf5d6bb61a805b44b58c.807541.xyz/api/v1/client/subscribe?token=e4625d4d5013ed8c116958af3c19c288
  - https://hongxing.one/hxvip?token=d78e943dcdc5c6fcb8b2a020e0b0d680
  - https://paste.ee/d/bXYNA2qE
  - https://v1.mk/KI0HYuI
  - https://cola.xn--chqu2nzsxv3y.com/api/v1/client/subscribe?token=15d07865b121b74348d5e6c78eb721fb
  - https://service-p0v9tp46-1312645837.gz.apigw.tencentcs.com/api/v1/client/subscribe?token=577a10ca85e1e2f2debb472698ac348a
  - https://api.jetcamoe.com/api/v1/public/services/119048/bdb054b4e35e6aeedd929942410d3b1c?agent=clash-verge
  - https://sea-5l8.pages.dev/CSDN
  - https://45.137.181.197/api/v1/client/subscribe?token=57141b33b664412b3254cd69853edc57
  - https://flynb.site/sub?token=oLKUUBC7cJPmouRzlnw2bg&tag=clash
  - https://rigengjiedian.one/api/system/subscribe
  - https://flynb.site/sub?token=oLKUUBC7cJPmouRzlnw2bg&tag=clash#不能用换代理工具nekobox_1.2.9用不了
  - https://douyun.sbs/api/v1/client/subscribe?token=11776a3bbe1d3b75e41d8ebd192fe962
  - https://miaosu.jiediandingyuejiji.homes/answer/land?token=1cb7fc118000154b491c1538db1d51e4
  - https://s.imgki.com/NXoIBha
  - https://v1.mk/pKCCe4n
  - https://tt.vg/GtPuI
  - https://v1.mk/1qsg3ze
  - https://aimanman.me/s/ec2522afc2ed398b37b41e63a0986603
  - https://gy777.xyz/s/eebcadef19d0753994ac580846be5e40
  - https://aimanman.me/s/88a7413463569ad5c92cf16b1b6f72e8
  - https://j.sub12345.org/link/ocT2Rf2F4yViw1yn?sub=3
  - https://skr.daozhang.site/v2ray
  - https://xn--4oq11ryli3rg.com/s/0194825bc83336ecd1971875905019df
  - https://aimanman.me/s/97aa2ccb36ef693e7986ad3a503a1cdb
  - https://gywanglug.xyz/s/08f978868acc79974cf025e569a9bfdc
  - https://paste.ee/d/w2827kEM
  - https://s.imgki.com/NXoIBha
  - https://xn--4oq11ryli3rg.com/s/238a43a3896447533664c04b20ee8fe6
  - https://j.sub12345.org/link/ocT2Rf2F4yViw1yn?sub=3
  - https://202503021722111.chibaba.ggff.net/api/v1/client/subscribe?token=2300c05a842f8ec6f55da6596882bfe3
  - https://xboard.520021.net/api/v1/client/subscribe?token=6b201047a6ad996d77fb8354a6a7696c
  - https://gywanglug.xyz/s/08f978868acc79974cf025e569a9bfdc
  - http://api.miloli.cc/api/v1/client/subscribe?token=d7ba70a11e5dbb2f5b6da8fbeea405df
  - https://xship.top/v1/subscribe?starlink=_RP5WBvhkvkfK72mu4gwgQtv
  - https://gaxcdn.koihost.com/apiv2/user/sub?token=a6286c863d094f6186fc55a33578b0ce
  - https://paste.ee/d/5HrrZ7Y8
  - https://gaxcdn.koihost.com/apiv2/user/sub?token=a6286c863d094f6186fc55a33578b0ce
  - http://api.miloli.cc/api/v1/client/subscribe?token=d7ba70a11e5dbb2f5b6da8fbeea405df
  - https://05.nfsq.us/api/v1/client/subscribe?token=3d6918bc30e87138f9da9ed5de5fcc3d
  - https://bajie.la/api/v1/client/subscribe?token=496b495b2b0c5fe8c92c73184510a756
  - http://ovh.xgjs1.xyz/api/v1/client/subscribe?token=4f45f8a0433b43825f661f456a49394a
  - https://app.mitce.com/?sid=236695&token=fcef9b19b8ae95f30787
  - https://www.yfjc.xyz/api/v1/client/subscribe?token=1ac4465d383e64633351f0edd2628769
  - https://gy888.xyz/s/563b099675750b0f8cad3e77c1009d29
  - https://api.otcopusvpn.cc:18008/sub/client/subscribe?token=4de417487a032169d046d656d28c4c59
  - https://g871cec.cdn.uunode.com/apiv2/user/sub?token=9972643bb6726e53ba44d1259949bc71