# 是否打印进度 
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 10
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 4096
  # 下载测试超时时间 单位秒
  download-timeout: 5
  # 测速下载大小 单位MB
  download-size: 50
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 2
  # 测速数量
  speed-count: 12
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  # 临时节点
  - 
  - 
  - 
  - https://sbgfw.trafficmanager.net/api/v1/client/subscribe?token=17ce4f1c0f22d29d4fe8aee584a17e91
  - https://link08.shanhai.one/api/v1/client/subscribe?token=8d4c465fd37cb8db170036cf00be9dbc#白嫖
  - https://www.ckckssl.top/api/v1/client/subscribe?token=cdc96d354d96b6e6e2670c7611611bdf#/能用的使劲刷，用光自动补满
  - https://xn--cp3a08l.com/api/v1/client/subscribe?token=183024e3b959f005edf06e562319a7b9
  - https://api-hx.02000.net/api/v1/client/subscribe?token=ced0a9b46562a06f25c952595b9fbee2
  - https://52pokemon.xz61.cn/api/v1/client/subscribe?token=6b3aee4b1f36003578311ed5d3f52835
  - https://1rzy6c5.wxll4.cfd/api/v1/client/subscribe?token=aaeeafc2936e179b5b88430677a401d9
  - https://sub.miaolianyun.vip/mly_sub?token=17798f36a432a1ccaeb6ea0744cfd10b
  - https://sub.pumcloud.net/s/9a7cf3a2ecd704e7024e69f66def0ca2
  - https://www.cross666.top:9423/s/7ead2ccbd3f4d3cb19d8d7fcb21bb152
  - https://www.cross666.top:9423/s/7ead2ccbd3f4d3cb19d8d7fcb21bb152
  - http://47.243.161.149/link/Tbulm4VyWGtGRANZ?clash=2
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA
  - https://www.tiziwrops.com/api/v1/client/subscribe?token=8fa788726eb4b5323e2d19297d5147e1
  - https://sub.mogufan.com/s/224878231a8a55e73d7e1bacef80129d
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=be30e81980997f794f9b4660ed1bbd5d
  - https://s1.byte11.com/api/v1/client/subscribe?token=9ec69a0e00ac747ae2d0f2976d920485
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA#%E6%98%9F%E9%93%BEStarlink%20%E2%9C%A8
  - https://s1.byte11.com/api/v1/client/subscribe?token=9ec69a0e00ac747ae2d0f2976d920485
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=be30e81980997f794f9b4660ed1bbd5d#/2.2mb/s(20mbps)
  - https://s1.byte11.com/api/v1/client/subscribe?token=9ec69a0e00ac747ae2d0f2976d920485#/感觉限制设备_请正在用的先用20x节点
  - https://s1.byte11.com/api/v1/client/subscribe?token=9ec69a0e00ac747ae2d0f2976d920485#/有20x
  - https://hongxingdl.love/hxyunvip?token=79156110324e7f223c6994e9986c30aa
  - https://6bsub.zhunchuanpb.com/api/v1/client/subscribe?token=9073771badd26857dd11f3d1bc15803f
  - https://s1.byte11.com/api/v1/client/subscribe?token=9ec69a0e00ac747ae2d0f2976d920485
  - http://47.74.1.114:8089/api/v1/client/subscribe?token=d26fb71f53778d63fcf7a7829754d592
  - http://47.74.1.114:8089/api/v1/client/subscribe?token=36dfcf9d512d48b1059a09205c6b53fe
  - https://prof.222222212.xyz/api/v1/client/subscribe?token=81f7550bca1e4695787ecf5322e24a40
  - https://prof.222222212.xyz/api/v1/client/subscribe?token=81f7550bca1e4695787ecf5322e24a40#/有0x节点
  - https://1.bethebest.eu.org/api/v1/client/subscribe?token=846d0801c50b4d5bc700617a1e38caaf
  - https://app.mitce.com/?sid=242223&token=4c8df7a731a25bd17378
  - http://202504081152261.chibaba.ggff.net/api/v1/client/subscribe?token=051c04e9267e21b120fcce358401472e
  - https://666676666.xyz/api/v1/client/subscribe?token=dc8260cdabfb187bf48f5963ea032678
  - https://nxsubnx.hhkkdd.cn/api/v1/client/subscribe?token=e46318fcbfbecc08e348004fb051b4ba
  - https://www.ckckssl.top/api/v1/client/subscribe?token=cdc96d354d96b6e6e2670c7611611bdf
  - https://epclub.xyz/api/epclub?token=661b0c35617674155d32245752135d11#/快刷
  - https://www.ckckssl.top/api/v1/client/subscribe?token=cdc96d354d96b6e6e2670c7611611bdf
  - https://bailian.uk/s/5f9b934a7aa9e26132bf084f7afd100d
  - https://bailian.uk/s/4c22f5dbc9b60b3d0c8dbdfd0c93f1bf
  - https://dfjc.xyz/api/doufu?token=4caecf32d325b35a1cd2f80f1012fb39
  - https://dfjc.xyz/api/doufu?token=5df0b2d1e973fe148a9bf89cb04cb0cf
  - https://checkhere.top/link/BDj1CQ2FUJwHnOR3?clash=1
  - https://as.al/raw/P6Pr1D
  - http://8.129.23.122/s/5fc9a1457054d335feb23235bd8b9225
  - https://npccloud.top/api/v1/client/subscribe?token=9f008a488c2155ad52e1674edb96d749
  - https://202503212313501.chibaba.ggff.net/api/v1/client/subscribe?token=eee1b58c52d8e656bc6b729a182cf49b
  - https://ywl.201593.xyz/s/44d8b94f3591df9e4376ceb5c5cca080
  - https://api.dler.io/sub?target=clash&url=https%3A%2F%2F05.huyooo.zip%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D8ee04b7fcd2bee76b8c918b4ddd0512e&insert=false
  - https://05.huyooo.zip/api/v1/client/subscribe?token=8ee04b7fcd2bee76b8c918b4ddd0512e
  - https://npccloud.top/api/v1/client/subscribe?token=9f008a488c2155ad52e1674edb96d749
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=be30e81980997f794f9b4660ed1bbd5d
  - https://202503212313501.chibaba.ggff.net/api/v1/client/subscribe?token=eee1b58c52d8e656bc6b729a182cf49b
  - https://dfjc.xyz/api/doufu?token=56ee787cd95f50e53b26297c66b4eb55#/限制五设备连接
  - https://app.jisuba.live/s/1981e8cdc2e36df838306afe082cee39
  - https://app.jisuba.live/s/1f8cc339e262ef7f03c0e20ef4f8651b
  - https://202503212313501.chibaba.ggff.net/api/v1/client/subscribe?token=eee1b58c52d8e656bc6b729a182cf49b
  - https://app.jisuba.live/s/1f8cc339e262ef7f03c0e20ef4f8651b
  - https://app.jisuba.live/s/1981e8cdc2e36df838306afe082cee39
  - https://sub.ylkszy.eu.org/2025/F4/s4/c.yaml
  - https://ansuyun.xyz/api/as?token=329be9f6fc07ffff723c13ff6f478154
  - https://ansuyun.xyz/api/as?token=a0600c664805237ffa7df55a12fa049e
  - https://sub.xn--4gqvd492adjr.com/s/9ccbdc4b137c348c6e2cf814e5719aa9
  - https://sub.xn--4gqvd492adjr.com/s/6a401b142084ee1cbae1251e76f25118
  - https://ywl.201593.xyz/s/d866c2331afde8d0c32e9e121168534a
  - https://sub.521177.xyz/Jay
  - https://ywl.201593.xyz/s/932ef94591c7e742a6c56cfa4f027351
  - https://ywl.201593.xyz/s/d866c2331afde8d0c32e9e121168534a
  - https://ywl.201593.xyz/s/44ead6da115f4bc3301e0f8e382d278e
  - https://ywl.201593.xyz/s/932ef94591c7e742a6c56cfa4f027351
  - https://as.al/raw/c3KPOP
  - https://as.al/raw/zztbfX
  - https://msub.fengchiyx.xyz/api/v1/client/subscribe?token=34ff9012ec68f9c521fc559a83146eba
  - https://wub.zongyunti.site/api/v1/client/subscribe?token=34c21a865a0395ad161e749ac7048fd6#/这个有重置一个月之后等等看有没有流量
  - https://wub.zongyunti.site/api/v1/client/subscribe?token=34c21a865a0395ad161e749ac7048fd6
  - https://epclub.xyz/api/epclub?token=b8877e23d8e96dae30e161f3fad4d39a
  - https://epclub.xyz/api/epclub?token=a4ad607b25573b878ba4141766805d45
  - https://user937.dukadi.one/api/v1/client/subscribe?token=cd4dc73947ceeb7b9d3b91dc9b3c1ecf
  - https://ywl.201593.xyz/s/44d8b94f3591df9e4376ceb5c5cca080
  - https://dy11.baipiaoyes.com/api/v1/client/subscribe?token=2a942c0fbf528ff4da2ef2a479aaf7eb
  - https://ansuyun.xyz/api/as?token=cde510ad435f7a33e80d510322f87fee#/ansuyun.xyz
  - https://ansuyun.xyz/api/as?token=302f67c27fbfde92053176978707f327
  - https://link.onesy.link/link/kMkHYontpUfl7S06?clash=1
  - https://paste.ee/d/0e0spzmw
  - https://s.imgki.com/uKIBuVg
  - https://need01.keepprofit.top/api/v1/client/subscribe?token=1a1e29e85e4c35cd48329906a6c33595
  - https://need01.keepprofit.top/api/v1/client/subscribe?token=1a1e29e85e4c35cd48329906a6c33595#/有2x，速度8.5mb/s，带宽69mbps
  - https://need01.keepprofit.top/api/v1/client/subscribe?token=1a1e29e85e4c35cd48329906a6c33595#/有2x
  - https://www.flyintpro05.com/api/v1/client/subscribe?token=62be89e4bc828cdfd0c62bfb44746312
  - http://202503281226111.chibaba.ggff.net/api/v1/client/subscribe?token=be030b075cf4ba7afeeae4d3257fbdb8#/节点情况https://tz.chibaba.filegear-sg.me/
  - https://rgergergergerg6555.saojc.xyz/api/v1/client/subscribe?token=a29191a8042e2e2fb1f3a93d0f27c5b1
  - https://xingcloud.pwzvd.cn/api/v1/client/subscribe?token=992af925651ee5b47878f0abba2947d4
  - https://api.sraylink.com/api/client/?token=ff19aac0ee34ed7050411caf5f0c8538
  - https://rigengjiedian.one/api/system/subscribe
  - https://igdux.top/sNA4nHY75fiXA2jFCDd76a5d
  - https://igdux.top/AzJFReQ3nPNR5yYfXXrQ6rcx
  - https://book.hostnow.top/api/v1/client/subscribe?token=e1a90ec2dfd92a6a8f75b3b224ecfbaa
  - https://igdux.top/TwcchR34f7dGeH4Hza6nyfWF
  - https://paste.ee/d/R3fZLg5J
  - https://fsc.jiediandingyuejiji.homes/answer/land?token=ebf77cdb420eb8bd6ccc30564d9bd588
  - https://xn--mesz9ptugxg.com/api/v1/client/subscribe?token=dcb2eb6379a152bbe397572220e8e4a8
  - https://s1.byte16.com/api/v1/client/subscribe?token=ffc05e97d39d2efbdba15693857014a0
  - https://v2.ixlmo.net/api/v1/client/subscribe?token=67bc22d07a835ee03f143878b7f6199d
  - https://sub.verybigball.org/download-sub/?sid=151788&uid=3760&token=64e0e48a77343e4971fb&app=auto
  - https://sub.nexc.cc/api/v1/client/subscribe?token=6653dae74bb2813201976ce8561b37c8
  - https://sub.nexc.cc/api/v1/client/subscribe?token=8ed3fe4c475e3f339dbf760ae72667df
  - https://g15311cec.cdn.uunode.com/apiv2/user/sub?token=7fb4e06fd96e39cedd21e8ff66b00d48
  - https://xqsub.e54.site/api/v1/client/subscribe?token=27b0079c3c0c3f06630c42074a62be19
  - https://xqsub.e54.site/api/v1/client/subscribe?token=78406b68ace9653c493709dafde1634c
  - https://amvne.ofourl.xyz/link/VIP/ofoNET?token=7c47f0c1cb8acbc8b0470c4bff4a284c
  - https://g871cec.cdn.uunode.com/apiv2/user/sub?token=bebf85760972ff4b242529642eb36efb
  - https://pianyi.sub.sub.subsub123456789.com/answer/land?token=6764d0eab8283058a5521054fd09c1d5
  - https://ly.ccwink.cc/api/v1/client/subscribe?token=85ce9c6ba278c9f8e194bb98087382f0
  - https://fsc.jiediandingyuejiji.homes/answer/land?token=ebf77cdb420eb8bd6ccc30564d9bd588
  - https://sub.nexc.cc/api/v1/client/subscribe?token=6653dae74bb2813201976ce8561b37c8
  - https://sub.verybigball.org/download-sub/?sid=151783&uid=3752&token=c1f2ecf5ee4127d2d10b&app=auto
  - https://xqsub.e54.site/api/v1/client/subscribe?token=b9669d7ce0265a9be4265ae5a9d22d57
  - https://xqsub.e54.site/api/v1/client/subscribe?token=144b17a92ca77c9bc3c55e173d33c41a
  - https://xqsub.e54.site/api/v1/client/subscribe?token=27b0079c3c0c3f06630c42074a62be19
  # 总节点保存
  - https://ghproxy.net/https://raw.githubusercontent.com/mitjavaz/memo/master/allNodes.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub4.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub5.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub6.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub7.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub8.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub9.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub10.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vmess.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vless.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/trojan.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ss.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ssr.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/tuic.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/hysteria2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Warp_sub.txt
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  # TG #
  # 蛋黄酱节点分享：@FProxies
    # 0404节点
  - https://sub.danhu.ddns-ip.net/paste/jGd0KIXz3l5XmaLW/urls
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  - https://svip.xy666.ggff.net/auto
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/