# 是否打印进度 
print-progress: true

# 可选值 debug info warn error
log-level: info

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 10
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 5120
  # 下载测试超时时间 单位秒
  download-timeout: 4
  # 测速下载大小 单位MB
  download-size: 20
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 2
  # 测速数量
  speed-count: 20
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  # 临时节点
  # - 
  # - 
  # - 
  # - 
  # - 
  - https://paste.ee/d/0e0spzmw
  - https://s.imgki.com/uKIBuVg
  - https://sub.gougou.live/s/091bbd6b56c4bbe6f7fbf71758508db9
  - https://ling.lty88.net/sdsfwer45/dcc3b9fb764b2a5ec11a890aed2179a6
  - https://epclub.xyz/api/epclub?token=661b0c35617674155d32245752135d11
  - https://url.v1.mk/sub?target=clash&url=https%3A%2F%2Fepclub.xyz%2Fapi%2Fepclub%3Ftoken%3Ddab0227750891c82953faa26724a3854&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  - https://epclub.xyz/api/epclub?token=dab0227750891c82953faa26724a3854#/官网http://epclub.xyz
  - https://epclub.xyz/api/epclub?token=dab0227750891c82953faa26724a3854
  - https://epclub.xyz/api/epclub?token=dab0227750891c82953faa26724a3854#/填epc买第一个就能白嫖，不限制邮箱和邮箱后缀
  - https://epclub.xyz/api/epclub?token=1338bc19d1ea21dbe6b165745cdcdd69#/速度也就9mbps卡的一批
  - https://epclub.xyz/api/epclub?token=1338bc19d1ea21dbe6b165745cdcdd69
  - https://sub.tuanzi.xyz/s/3b40cce438f0f9c65fe250e52924b955
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=38b5d270f053b5ca4b754b6cfee6ae9e
  - https://need01.keepprofit.top/api/v1/client/subscribe?token=1a1e29e85e4c35cd48329906a6c33595
  - https://need01.keepprofit.top/api/v1/client/subscribe?token=1a1e29e85e4c35cd48329906a6c33595#/有2x，速度8.5mb/s，带宽69mbps
  - https://need01.keepprofit.top/api/v1/client/subscribe?token=1a1e29e85e4c35cd48329906a6c33595#/有2x
  - https://www.otcopusapp.cc/lx3af288h5i8pz380/api/v1/client/subscribe?token=bffd3c2732aa304ee380a012cbcfff40
  - https://app.mitce.com/?sid=243809&token=srvexrkz
  - https://sub.mangshe.org/api/v1/client/subscribe?token=319769ea1b6dfb63185908f3ac00da99#/20个hysteria2节点，延迟九百往上
  - https://sub.mangshe.org/api/v1/client/subscribe?token=319769ea1b6dfb63185908f3ac00da99
  - https://paste.ee/d/pM81vfU7
  - https://s.imgki.com/NeBQniU
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=38b5d270f053b5ca4b754b6cfee6ae9e#/用光自动补满，使劲刷
  - https://www.flyintpro05.com/api/v1/client/subscribe?token=62be89e4bc828cdfd0c62bfb44746312
  - https://sub.zzxxccvv.top/v8soc/c2as?token=a193620fb3bfdf4a850c10c360801486
  - https://202502181121431.chibaba.ggff.net/api/v1/client/subscribe?token=b5756287f05633d9068afb2a9fe375ba
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=38b5d270f053b5ca4b754b6cfee6ae9e
  - http://202503281226111.chibaba.ggff.net/api/v1/client/subscribe?token=be030b075cf4ba7afeeae4d3257fbdb8#/节点情况https://tz.chibaba.filegear-sg.me/
  - https://rgergergergerg6555.saojc.xyz/api/v1/client/subscribe?token=a29191a8042e2e2fb1f3a93d0f27c5b1
  - https://dwauhiaoawdibga.bikamanhua.top/sha/bi/gfw?token=4cf4ebb65941f084a8c7044dcfaad7cc#/低价机场不能白嫖
  - https://dwauhiaoawdibga.bikamanhua.top/sha/bi/gfw?token=4cf4ebb65941f084a8c7044dcfaad7cc
  - https://ch.owokkvsxks.store/api/v1/client/subscribe?token=b815a417769dfd4e1983bbeefd8d7f35
  - https://xqsub.e54.site/api/v1/client/subscribe?token=da00f231fd8bc87eb330e2e00ec53170
  - https://xingcloud.pwzvd.cn/api/v1/client/subscribe?token=992af925651ee5b47878f0abba2947d4
  - https://ch.owokkvsxks.store/api/v1/client/subscribe?token=679b8c493b6009a578cd75a64ea71066
  - https://xqsub.e54.site/api/v1/client/subscribe?token=5735bee9dd21a81f3cc6305d8bf5ae65
  - https://api.sraylink.com/api/client/?token=ff19aac0ee34ed7050411caf5f0c8538
  - https://ch.vfkum.website/api/v1/client/subscribe?token=aa36067d0aaafdb50bea5383ea099c72
  - https://rigengjiedian.one/api/system/subscribe
  - https://ywl.201593.xyz/s/8a8fde67d7657964d22fd9e661c9d7d5
  - https://sub.xn--mes91t7ofgnw.com/s/65b940f380bf45643b663ff7b44fb924
  - https://sub.xn--mes91t7ofgnw.com/s/7a6548269e81d9efd1a05240a515887d
  - https://sub.xn--mes91t7ofgnw.com/s/afd48b76e8d7e8c7dbb683dcba3b77c8
  - https://sub.xn--mes91t7ofgnw.com/s/cdbc5187a9da849956e4a00c64596550
  - https://igdux.top/sNA4nHY75fiXA2jFCDd76a5d
  - https://igdux.top/AzJFReQ3nPNR5yYfXXrQ6rcx
  - https://book.hostnow.top/api/v1/client/subscribe?token=e1a90ec2dfd92a6a8f75b3b224ecfbaa
  - https://igdux.top/TwcchR34f7dGeH4Hza6nyfWF
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=531e0be2dbbfc393dfac550abee6ce57
  - https://paste.ee/d/R3fZLg5J
  - https://fsc.jiediandingyuejiji.homes/answer/land?token=ebf77cdb420eb8bd6ccc30564d9bd588
  - https://xn--mesz9ptugxg.com/api/v1/client/subscribe?token=dcb2eb6379a152bbe397572220e8e4a8
  - https://v1.mk/7IkXyiR
  - https://v1.mk/BxTdHqC
  - https://prjcm.itr.lol/link/VIP/ofoNET?token=138790b1ab408e30b1fff9e4e0d114a4
  - https://s1.byte16.com/api/v1/client/subscribe?token=ffc05e97d39d2efbdba15693857014a0
  - https://v2.ixlmo.net/api/v1/client/subscribe?token=67bc22d07a835ee03f143878b7f6199d
  - https://sub.verybigball.org/download-sub/?sid=151788&uid=3760&token=64e0e48a77343e4971fb&app=auto
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c0d689384b0f7f0362940e126b7a4a63
  - https://sub.nexc.cc/api/v1/client/subscribe?token=6653dae74bb2813201976ce8561b37c8
  - https://sub.nexc.cc/api/v1/client/subscribe?token=8ed3fe4c475e3f339dbf760ae72667df
  - https://s1.byte33.com/api/v1/client/subscribe?token=864188658b08e49f16ced2969513e47c
  - https://g15311cec.cdn.uunode.com/apiv2/user/sub?token=7fb4e06fd96e39cedd21e8ff66b00d48
  - https://xqsub.e54.site/api/v1/client/subscribe?token=df86b7f78767c9dbc46e447d74d60097
  - https://xqsub.e54.site/api/v1/client/subscribe?token=df46d6a227769469523c2eb2c8d5b5ee
  - https://xqsub.e54.site/api/v1/client/subscribe?token=0f535ce035f582453bf47bfd027b0243
  - https://xqsub.e54.site/api/v1/client/subscribe?token=13f94a3c83abb2a248e46dd37621f9de
  - https://xqsub.e54.site/api/v1/client/subscribe?token=519170be32226978a75ebc9ec38813dd
  - https://xqsub.e54.site/api/v1/client/subscribe?token=144b17a92ca77c9bc3c55e173d33c41a
  - https://xqsub.e54.site/api/v1/client/subscribe?token=f6f20d728dc4dc7307572fee8116b08d
  - https://xqsub.e54.site/api/v1/client/subscribe?token=27b0079c3c0c3f06630c42074a62be19
  - https://xqsub.e54.site/api/v1/client/subscribe?token=b9669d7ce0265a9be4265ae5a9d22d57
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c995b9ab2b53f2f49b80bb1273472b93
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c0d689384b0f7f0362940e126b7a4a63#/0元白嫖机场，注册不验证
  - https://xqsub.e54.site/api/v1/client/subscribe?token=a324065263835ed0a596d96872c3886f
  - https://xqsub.e54.site/api/v1/client/subscribe?token=78406b68ace9653c493709dafde1634c
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=531e0be2dbbfc393dfac550abee6ce57#用光自动补满
  - https://amvne.ofourl.xyz/link/VIP/ofoNET?token=7c47f0c1cb8acbc8b0470c4bff4a284c
  - https://g871cec.cdn.uunode.com/apiv2/user/sub?token=bebf85760972ff4b242529642eb36efb
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=531e0be2dbbfc393dfac550abee6ce57
  - https://pianyi.sub.sub.subsub123456789.com/answer/land?token=6764d0eab8283058a5521054fd09c1d5
  - https://pianyi.sub.sub.subsub123456789.com/answer/land?token=bbb3a9f81235c1d763cad3cae8188be5
  - https://ly.ccwink.cc/api/v1/client/subscribe?token=85ce9c6ba278c9f8e194bb98087382f0
  - https://fsc.jiediandingyuejiji.homes/answer/land?token=ebf77cdb420eb8bd6ccc30564d9bd588
  - https://sub.nexc.cc/api/v1/client/subscribe?token=8ed3fe4c475e3f339dbf760ae72667df
  - https://sub.nexc.cc/api/v1/client/subscribe?token=6653dae74bb2813201976ce8561b37c8
  - https://sub.verybigball.org/download-sub/?sid=151788&uid=3760&token=64e0e48a77343e4971fb&app=auto
  - https://sub.verybigball.org/download-sub/?sid=151783&uid=3752&token=c1f2ecf5ee4127d2d10b&app=auto
  - https://s.yyzzyyds.xyz/yyzz/114514/subscribe/c8ef81b8c2d18c41b276bc0a7cf4c1ec
  - https://s.yyzzyyds.xyz/yyzz/114514/subscribe/7c0c89371d3a43136028aff8a7b43f9e
  - https://xqsub.e54.site/api/v1/client/subscribe?token=f6f20d728dc4dc7307572fee8116b08d
  - https://xqsub.e54.site/api/v1/client/subscribe?token=b9669d7ce0265a9be4265ae5a9d22d57
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c995b9ab2b53f2f49b80bb1273472b93
  - https://xqsub.e54.site/api/v1/client/subscribe?token=144b17a92ca77c9bc3c55e173d33c41a
  - https://xqsub.e54.site/api/v1/client/subscribe?token=27b0079c3c0c3f06630c42074a62be19
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c0d689384b0f7f0362940e126b7a4a63
  - http://em7.buzz/v3/subscr?id=d5363e1171244baab0a1dbd5ac69630c
  # 总节点保存
  - https://ghproxy.net/https://raw.githubusercontent.com/mitjavaz/memo/master/allNodes.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://ghproxy.net/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  # TG #
  # 蛋黄酱节点分享：@FProxies
    # 0208节点
  - https://sub.danhu.ddns-ip.net/paste/OmJ9zWdyc6ZN9aAe/clash
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto