# 是否打印进度 
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 10
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 2999
  # 下载测试超时时间 单位秒
  download-timeout: 3
  # 测速下载大小 单位MB
  download-size: 10
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 2
  # 测速数量
  speed-count: 44
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  # 临时节点
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - https://ylks.tt2000.sbs/2025/F4/z8/c.yaml
  - https://x.juzi.lat/view.php?id=78cc61a1f338bdce
  - https://www.roc-taiwan.taipei/link/6vY3rvkzoG0S5jAU?clash=1
  - https://1.bethebest.eu.org/api/v1/client/subscribe?token=2a561d32ef721499be999eae9e3fe296
  - https://dash.sinqin.net/s/7d2b1e3bc02fe7dc9e5f92968bf63a5f
  - https://qishuijc.top/api/v1/client/subscribe?token=cc53778b817939d8fd581cc1ed943abc
  - https://qishuijc.top/api/v1/client/subscribe?token=732e0bf0dea00ad0228ec3e01ee15689
  - https://qishuijc.top/api/v1/client/subscribe?token=dfdf7bd5d413a113a9aef80e3de800db
  - http://38.55.97.141:12321/api/v1/client/subscribe?token=9097094bffd0ef62438c3d25c905bbdc
  - http://38.55.97.141:12321/api/v1/client/subscribe?token=05de311185300e6c432a4c1ad0bedaf9
  - http://38.55.97.141:12321/api/v1/client/subscribe?token=40319d15c29741d74405bfc01ecb744e
  - http://38.55.97.141:12321/api/v1/client/subscribe?token=2d67ba714cf0d61aa965cd1d70e1b89e
  - http://em7.buzz/v3/subscr?id=5be76fa537584282bb54b1efabd6ba3d
  - https://dash.sinqin.net/s/7d2b1e3bc02fe7dc9e5f92968bf63a5f
  - https://qishuijc.top/api/v1/client/subscribe?token=732e0bf0dea00ad0228ec3e01ee15689
  - https://qishuijc.top/api/v1/client/subscribe?token=cc53778b817939d8fd581cc1ed943abc
  - https://qishuijc.top/api/v1/client/subscribe?token=dfdf7bd5d413a113a9aef80e3de800db
  - https://v1.mk/1rathw1
  - https://v1.mk/AzqTJ7K
  - https://v1.mk/1bvCAWZ
  - https://v1.mk/1HB0KPz
  - https://v1.mk/oFqp5Av
  - https://v1.mk/ACT7pM6
  - https://v1.mk/wpnt2BR
  - https://v1.mk/EGNPuJu
  - https://v1.mk/QQGLm5q
  - https://submit.xz61.cn:23443/api/v1/client/subscribe?token=696d0b1f92df46059f9c923cf5320232
  - https://tt.vg/OrddG
  - https://bh.jiedianxielou.workers.dev/
  - https://igdux.top/CKnRRPmmX54fCcachC5aaQ2h
  - https://x.juzi.lat/view.php?id=4f791577a9bfaaf8
  - https://nano.nachoneko.cn/api/v1/client/subscribe?token=15c8b2771610ae4fe00282f1035a44d9
  - https://666676666.xyz/api/v1/client/subscribe?token=f701ce71294b488eebc00937d841bebb
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA
  - https://n063ww4.wxll4.cfd/api/v1/client/subscribe?token=676782dc6736a2f0d89f4f42b7e884e8
  - https://sub.miaolianyun.vip/mly_sub?token=17798f36a432a1ccaeb6ea0744cfd10b
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA
  - https://www.tiziwrops.com/api/v1/client/subscribe?token=8fa788726eb4b5323e2d19297d5147e1
  - https://xship.top/v1/subscribe?starlink=pro@ak22RsujzCYUkcqv_cU6ILMA#%E6%98%9F%E9%93%BEStarlink%20%E2%9C%A8
  - https://6bsub.zhunchuanpb.com/api/v1/client/subscribe?token=9073771badd26857dd11f3d1bc15803f
  - https://1.bethebest.eu.org/api/v1/client/subscribe?token=846d0801c50b4d5bc700617a1e38caaf
  - https://666676666.xyz/api/v1/client/subscribe?token=dc8260cdabfb187bf48f5963ea032678
  - https://nxsubnx.hhkkdd.cn/api/v1/client/subscribe?token=e46318fcbfbecc08e348004fb051b4ba
  - https://link.onesy.link/link/kMkHYontpUfl7S06?clash=1
  - https://www.flyintpro05.com/api/v1/client/subscribe?token=62be89e4bc828cdfd0c62bfb44746312
  - https://rgergergergerg6555.saojc.xyz/api/v1/client/subscribe?token=a29191a8042e2e2fb1f3a93d0f27c5b1
  - https://api.sraylink.com/api/client/?token=ff19aac0ee34ed7050411caf5f0c8538
  - https://rigengjiedian.one/api/system/subscribe
  - https://igdux.top/sNA4nHY75fiXA2jFCDd76a5d
  - https://igdux.top/AzJFReQ3nPNR5yYfXXrQ6rcx
  - https://book.hostnow.top/api/v1/client/subscribe?token=e1a90ec2dfd92a6a8f75b3b224ecfbaa
  - https://igdux.top/TwcchR34f7dGeH4Hza6nyfWF
  # 总节点保存
  - https://raw.githubusercontent.com/mitjavaz/memo/master/allNodes.yaml
  - https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub4.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub5.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub6.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub7.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub8.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub9.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub10.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vmess.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vless.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/trojan.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ss.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ssr.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/tuic.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/hysteria2.txt
  - https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Warp_sub.txt
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  # TG #
  # 蛋黄酱节点分享：@FProxies
    # 0404节点
  - https://sub.danhu.ddns-ip.net/paste/0aLyIfZNNKGnpKW9/urls
  - https://sub.danhu.ddns-ip.net/paste/jGd0KIXz3l5XmaLW/urls
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  - https://svip.xy666.ggff.net/auto
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/