# 是否打印进度
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: regex
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 120
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://www.youtube.com/generate_204
  # alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 5000
  # 最低测速 单位KB/s
  min-speed: 9999
  # 下载测试超时时间 单位秒
  download-timeout: 4
  # 测速下载大小 单位MB
  download-size: 40
  # 测速地址
  speed-test-url:
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  speed-skip-name: 
  # 测速并发
  speed-check-concurrent: 6
  # 测速数量
  speed-count: 14
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  - 
  - 
  - 
  - https://mly1.543412546.xyz/api/v1/client/subscribe?token=566a3e6f70e6684ea566b4b2c667d9f9
  - https://bbq.mcwy.xyz/api/v1/client/subscribe?token=PdJ8xNRMTarL2mIZ
  - https://1122.yunjijd.xyz/api/v1/client/subscribe?token=13343394fd788ed97031b3883a81df00
  - https://v1.mk/YYs6esF
  - https://tt.vg/AnoRG
  - https://v1.mk/QHIdDWs
  - https://v1.mk/0GSvtVR
  - https://v1.mk/CUsAx57
  - https://vpn.huasuan666.top/api/v1/client/subscribe?token=f17451dcf9b384087f50f78a9350a57d
  - https://1122.yunjijd.xyz/api/v1/client/subscribe?token=1268cf24b806b61bfe96e0f46748df77
  - https://sub.cloudtaste.xyz/tastegood/781ccb7638902080f31c0b69a56af020
  - https://sub.cloudtaste.xyz/tastegood/bbf001f0c6ba32af4855c1bee077726d
  - https://tc.ztcloud.xyz/api/v1/client/subscribe?token=26cec3bda11795769be5d18126c4b354
  - https://jsjc.cfd/api/v1/client/subscribe?token=47ebed86881bbfd2cd21810284ec0b13
  - https://v1.mk/KRSSHmZ
  - https://dy11.baipiaoyes.com/api/v1/client/subscribe?token=44d630622d921db99f73216300e45020
  - https://v1.mk/TlMleMt
  - https://tc.ztcloud.xyz/api/v1/client/subscribe?token=306a110108f8023ac36da0fc46cdfe51
  - https://tc.ztcloud.xyz/api/v1/client/subscribe?token=3550c988f606049cd74a4fb5cfdbb80b
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=a48109b565ecfc0a98f45816d3f9e161
  - https://tc.ztcloud.xyz/api/v1/client/subscribe?token=306a110108f8023ac36da0fc46cdfe51
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=7b74dc814799449675239d0d3157a9f0
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=3f4c0707a344b7465f1e577ca78808f8
  - https://gw.ztcloud.xyz/api/v1/client/subscribe?token=15b50bc1649a8e7eeed63517b6e74e05
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=c1719afa23a5a5e915948a669e4231ce
  - https://gw.ztcloud.xyz/api/v1/client/subscribe?token=704233cd6999885589a8c23dbcfbf58f
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=d80acfd6e77a27f923afb63130335df6
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=360490724a9853a2df5bb3e56f4c8af7
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=d450c2aefda4a2187f6da68dc42d00c2
  - https://tc.ztcloud.xyz/api/v1/client/subscribe?token=26cec3bda11795769be5d18126c4b354
  - https://w258963147.ztcloud.xyz/api/v1/client/subscribe?token=3c627aadae031ef190993b7447c0bb10
  - https://subapi.v1.mk/remoteconfig/2025/06/0626/60757aee959275fded3fd2d45f0fe318.ini
  - https://subapi.v1.mk/remoteconfig/2025/06/0625/3eb547f64379f86d0e6f4105b2473da4.ini
  - https://subapi.v1.mk/remoteconfig/2025/06/0621/59247e590462d689f01a511592b6eb99.ini
  - https://subapi.v1.mk/remoteconfig/2025/06/0621/3b901b7d03cb7cde3a545d8d4cdd04ad.ini
  - https://subapi.v1.mk/remoteconfig/2025/06/0620/156bd7bdf33a7640401557203d818494.ini
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1
  - https://ooooooo.vvvv.ee/O
  - https://kkkkkkk.vvvv.ee/K
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1&flag=meta
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1&flag=meta
  - https://ylks.tt2000.sbs/2025/F4/x18/c.yaml
  - https://fly0001.buzz/gateway/feitu?token=af2b7c2e52fd794814c6f2ea7a06120e
  - https://sub.xn--mes358awwugpa.com/sub?token=552d8dc592e368f9438dff0061c1d9fe
  - https://ylks.tt2000.sbs/2025/F4/s17/c.yaml
  - https://ylks.tt2000.sbs/2025/F4/u16/c.yaml
  - https://vpn.huasuan666.top/api/v1/client/subscribe?token=c384811f63c704a7cd6e98a6c87f79fc
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=47b575570f529022d5778582572db59e
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=b10f75a290433b946d009600b05368a5
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=5810a6ae993d64cedc6f8ec5ebac043a
  - https://hs.huasuan666.top/api/v1/client/subscribe?token=02817e08b4676029b91d612843be9b1a
  - https://hs.huasuan666.top/api/v1/client/subscribe?token=39fd8e901d4da2b6c0bf56add49b4dca
  - https://vpn.huasuan666.top/api/v1/client/subscribe?token=ef8b67b92eb9927e21195397b3d04a03
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=b10f75a290433b946d009600b05368a5
  - https://ylks.tt2000.sbs/2025/F4/v13/c.yaml
  - https://ylks.tt2000.sbs/2025/F4/11n/c.yaml
  - https://tc.qy1357.top/api/v1/client/subscribe?token=99843c5ab80547cfb0a55516f6b0d0e7
  - https://vip.subscribe-needay.xyz/api/v1/client/subscribe?token=a87d6b8525451894286843fa4eae592b
  - https://95.qy1357.top/api/v1/client/subscribe?token=b2b644a2ba32aada7dfb5859c59e36a3
  - https://getinfo.bigwatermelon.org/s?token=d6ffddb3abf6fcf9288dc26937156397
  - https://getinfo.bigwatermelon.org/s?token=70fd57dcf823931c4a6cd5909421711d
  - https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5
  - https://e.db01.in/link/7nOpKBwclgYbweua?clash=1
  - https://www.dabai.in/link/O4SwmMZ1eEaBoH1O?clash=1
  - https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5
  - https://www.dabai.in/link/O4SwmMZ1eEaBoH1O?clash=1
  - https://dy11.baipiaoyes.com/api/v1/client/subscribe?token=5ff2c5ce71d1b68af9a39691adf71a64
  - https://api-bigbear-v2-sub.sodtool.com/subscribe/universal?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEzNTA4NTMsInVzZXJJZCI6ImRhMmQ3ZjUyZTFiMjQ2NDc4NTM1YmI3ODYyZDJjY2QwIn0.dp3QF6CeYaWm46Hc_LBg_bhKcjcP3GK5wGhISpcpFvI&device_type=
  - http://13.248.254.117/sub/295c1a32b309293c/clash/%E9%A3%9E%E9%B8%9F%E5%8A%A0%E9%80%9F?route=0
  - https://api.x5533.cn/api/v1/cliont/svbhghcribe?token=5ef2b17a1be6469e051d0f58f35c8b23
  - https://a.545437.xyz/jiji?token=e6131819bcf560b8f3e28180339efe44
  - https://nano.nachoneko.cn/api/v1/client/subscribe?token=76f11057c2731a948cc6d0ab9b9bd313
  # TG #
  # 蛋黄酱节点分享：@FProxies
  # 0705节点
  - https://sub.danhu.ddns-ip.net/paste/250705BlryF8IGFh/base64
  - https://sub.danhu.ddns-ip.net/paste/250705BlryF8IGFh/clash
  - https://sub.danhu.ddns-ip.net/paste/250705BlryF8IGFh/urls
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  - https://svip.xy666.ggff.net/auto
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/
  # 总节点保存
  - https://ghproxy.net/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://ghproxy.net/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.txt
  # 备用节点
  - https://ghproxy.net/https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Roywaller/clash_subscription/refs/heads/main/clash_subscription.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/clash/naidounode.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/mgit0001/test_clash/refs/heads/main/heima.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/README.md
  - https://ghproxy.net/https://raw.githubusercontent.com/Pawdroid/Free-servers/refs/heads/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/shahidbhutta/Clash/refs/heads/main/Router
  - https://ghproxy.net/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml