# 是否打印进度
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 120
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://www.youtube.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 14999
  # 下载测试超时时间 单位秒
  download-timeout: 3
  # 测速下载大小 单位MB
  download-size: 50
  # 测速地址
  speed-test-url:
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 2
  # 测速数量
  speed-count: 18
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - https://mot.luyuju.dpdns.org/dyRkcYMfQavqC0wMghhv
  - https://mot.gike.dpdns.org/N49o8kZF0qp0447j3kyc
  - https://mikuyo.bpd67081tsq.ddns-ip.net/xe3K5Bi0FsU2VxAb5aXi
  - https://ennyfe.zipgd3vx91o.ddns-ip.net/wen1u1aHn4kahKQeQN8j
  - https://mot.morisi.ggff.net/Y1JRPHZXm4LXM6R9MRzi
  - https://miku.mikuru.ip-ddns.com/nYMU6Xk61WsKCCXF941K
  - https://oty.myto.ip-ddns.com/jJh3s4xu97d5eNPi7e0T
  - https://mihu.sorry.ip-ddns.com/6oFtgiYFBA77zDwFRA4b
  - https://etc.mesa.ip-ddns.com/9g4C1UAZeaBQD86WfCV0
  - http://162.19.79.201:81/s/e6e55e604068e3fa29d5471863126890
  - https://link.nertron.com/api/nertron/link/subscribe?token=bc21ec986634fbd53edab4d6d7124052
  - https://getinfo.bigwatermelon.org/s?token=d6ffddb3abf6fcf9288dc26937156397
  - https://getinfo.bigwatermelon.org/s?token=70fd57dcf823931c4a6cd5909421711d
  - https://api.bppp.shop/api/sub/5f71bc8019b1d93ac6b0230a43f38840
  - https://api.bppp.shop/api/sub/921af3220df0280315f9c45c14622e6a
  - https://tiamocloud.top/s/5ad6709122c938a83b1ce74590a65c84#dingyue_Center
  - https://tiamocloud.top/s/26034c19ded29b0b7fc19d91456cd81a
  - https://sub.xn--vpn-3f0h822m.com/s/6e90e56a54c401970721aff9f65bc7c9
  - https://submit.xz61.cn:23443/api/v1/client/subscribe?token=ba8afba7e1b7b038d364243ecb7738d6
  - https://v1.mk/N3FkhpK
  - https://sub.yiliujichang.com/s/6b86e6dd5e352a55dea8d95079296f1c
  - https://sub.yiliujichang.com/s/9d66a6c5f55ef28669d0bd5e074592f1
  - https://sub.yiliujichang.com/s/64a6c89e5673c6cf206526ab8bcf2cca
  - https://sub.yiliujichang.com/s/708cebad42d5c3b4a25a03daf196c5c1
  - https://sub.yiliujichang.com/s/28062f8f46198f67ef693fb2ba5c77bf
  - https://sub.yiliujichang.com/s/7e50a0fd3fb8e629df48604ae6362511
  - https://sub.372372.xyz/api/v1/client/subscribe?token=87fd1239fa2282b2a01661ba42e28a87
  - https://sub.372372.xyz/api/v1/client/subscribe?token=024e356371111d8f84b0d93052868143
  - https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5
  - https://xb.inekokkk.com/amei/0f8cfa314e2232b2985e3827daaa6a97
  - https://e.db01.in/link/7nOpKBwclgYbweua?clash=1
  - https://www.dabai.in/link/O4SwmMZ1eEaBoH1O?clash=1
  - https://v1.mk/DId0Sel
  - https://v1.mk/r3UnDcC
  - https://sub.yiliujichang.com/s/6b86e6dd5e352a55dea8d95079296f1c
  - https://sub.yiliujichang.com/s/7e50a0fd3fb8e629df48604ae6362511
  - https://sub.yiliujichang.com/s/9d66a6c5f55ef28669d0bd5e074592f1
  - https://sub.yiliujichang.com/s/28062f8f46198f67ef693fb2ba5c77bf
  - https://sub.yiliujichang.com/s/64a6c89e5673c6cf206526ab8bcf2cca
  - https://sub.yiliujichang.com/s/708cebad42d5c3b4a25a03daf196c5c1
  - https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5
  - https://b3b0549e-160e-495a-a528-cccf5148bc48.372372.xyz/api/v1/client/subscribe?token=db8f691dbae4050ab22e5fe68351befb
  - https://sub.372372.xyz/api/v1/client/subscribe?token=024e356371111d8f84b0d93052868143
  - https://sub.372372.xyz/api/v1/client/subscribe?token=87fd1239fa2282b2a01661ba42e28a87
  - https://d7b12d59-21aa-9561-087f-89c834ac7fe8.372372.xyz/api/v1/client/subscribe?token=67ad098e7e4f784d5df85120820c6385
  - https://sub.372372.xyz/api/v1/client/subscribe?token=87fd1239fa2282b2a01661ba42e28a87
  - https://www.dabai.in/link/O4SwmMZ1eEaBoH1O?clash=1
  - https://sub.tsjc.shop/api/t/e147f5c6a6f0acb7419a688ac99fc73d
  - https://sub.tsjc.shop/api/t/9d8cdf21310221fda83cdc45b0a56ccb
  - https://sub.tsjc.shop/api/t/e147f5c6a6f0acb7419a688ac99fc73d
  - https://v1.mk/r3UnDcC
  - https://api-hy.02000.net/api/v1/client/subscribe?token=8ce51f4aa999c9641af7a211caf3d944
  - https://aac.wzai.top/api/v1/client/subscribe?token=412849dc4423a69d00e7e9600be8e62a
  - https://dy11.baipiaoyes.com/api/v1/client/subscribe?token=5ff2c5ce71d1b68af9a39691adf71a64
  - https://api-bigbear-v2-sub.sodtool.com/subscribe/universal?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEzNTA4NTMsInVzZXJJZCI6ImRhMmQ3ZjUyZTFiMjQ2NDc4NTM1YmI3ODYyZDJjY2QwIn0.dp3QF6CeYaWm46Hc_LBg_bhKcjcP3GK5wGhISpcpFvI&device_type=
  - http://13.248.254.117/sub/295c1a32b309293c/clash/%E9%A3%9E%E9%B8%9F%E5%8A%A0%E9%80%9F?route=0
  - https://yx1.281968.xyz/api/v1/client/subscribe?token=6b118824094f41726991c896c900d756
  - https://v1.mk/3rjadZJ
  - https://ocean.likelike.ip-ddns.com/O
  - http://sub3.127665.xyz/s/44b688c5860116b000a8c0d12e76db92
  - https://v1.mk/k1wjFTn
  - https://api.x5533.cn/api/v1/cliont/svbhghcribe?token=5ef2b17a1be6469e051d0f58f35c8b23
  - https://v1.mk/nMfUGUB
  - https://v1.mk/Bzu8tKp
  - https://v1.mk/whfxWhy
  - https://v1.mk/28JXDGe
  - http://207.170.66.146:50209/share/sub/node9PB?token=6rf8MzrhV_sKXhSg6icl3
  - https://a.545437.xyz/jiji?token=e6131819bcf560b8f3e28180339efe44
  - https://love-coffee.one/api/v1/client/subscribe?token=094f2731f13cce1039b001ad82d2beaf
  - https://nano.nachoneko.cn/api/v1/client/subscribe?token=76f11057c2731a948cc6d0ab9b9bd313
  - https://app.mitce.net/?sid=261147&token=srvnqrvq#?sid=261147&token=srvnqrvq
  - https://user7588.eyudy.one/api/v1/client/subscribe?token=64aef9e2b551b427214bf2e4b94d2d0b
  # TG #
  # 蛋黄酱节点分享：@FProxies
  # 0404节点
  - https://sub.danhu.ddns-ip.net/paste/K1nbSiOepiWBQ87T/base64
  - https://sub.danhu.ddns-ip.net/paste/K1nbSiOepiWBQ87T/clash
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  - https://svip.xy666.ggff.net/auto
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/
  # 总节点保存
  - https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/subs-check_Windows_x86_64/output/all.yaml
  # Github共享节点
  - https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.txt
  # 备用节点
  # - "https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml"
  # - "https://raw.githubusercontent.com/Roywaller/clash_subscription/refs/heads/main/clash_subscription.txt"
  # - "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml"
  # - "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml"
  # - "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml"
  # - "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml"
  # - "https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml"
  # - "https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/clash/naidounode.txt"
  # - "https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml"
  # - "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml"
  # - "https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml"
  # - "https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml"
  # - "https://raw.githubusercontent.com/leetomlee123/freenode/refs/heads/main/README.md"
  # - "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml"
  # - "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml"
  # - "https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml"
  # - "https://raw.githubusercontent.com/mgit0001/test_clash/refs/heads/main/heima.txt"
  # - "https://raw.githubusercontent.com/mai19950/clashgithub_com/refs/heads/main/site"
  # - "https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/README.md"
  # - "https://raw.githubusercontent.com/Pawdroid/Free-servers/refs/heads/main/sub"
  # - "https://raw.githubusercontent.com/shahidbhutta/Clash/refs/heads/main/Router"
  # - "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml"
  # - "https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/clash.yaml"
  # - "https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml"
  # - "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml"
  # - "https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml"
  # - "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
  # - "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/main/all_configs.txt"
  # - "https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
  # - "https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml"
  # - "https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml"