# 是否打印进度
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 120
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://www.youtube.com/generate_204
  # alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 9999
  # 下载测试超时时间 单位秒
  download-timeout: 4
  # 测速下载大小 单位MB
  download-size: 40
  # 测速地址
  speed-test-url:
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  speed-skip-name: 
  # 测速并发
  speed-check-concurrent: 5
  # 测速数量
  speed-count: 14
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - https://igdux.top/HSDr
  - https://gogof.hgfastgo.com/api/v1/client/subscribe?token=506d4358ba171eed3a516e7f21436975
  - https://gogof.hgfastgo.com/api/v1/client/subscribe?token=b294a9be1f2b6ad355a60c29e3e65f7b
  - http://gw-zubknq2tly.1010520.click/api/v1/client/subscribe?token=0985b7b96ce09745d2f3fa9fcb4a4243&flag=meta
  - https://app.mitce.net/?sid=315868&token=srvcdbfj
  - https://zhuzhuzhu.whtjdasha.com/api/v1/client/subscribe?token=920bd6c0538a16dbd568415badba5%E5%9B%9Bda
  - https://subyellow.bigbigwatermelon.com/s/c1d500a86d8e6e43b113e3a90736b133
  - https://www.tianj.icu/a/caa55ffb85474e137b298b010fcdf98e
  - https://odysseycdn.cyou/api/v1/client/subscribe?token=6acb961f4a5d0c12a15b604a9605ce94
  - https://mojie.app/api/v1/client/subscribe?token=0a052dd65193332621d52ff38e5c1717
  - https://cloud.gomeow.tech/gogo/78d999a36188743c9de4c40b01836624
  - http://shiyuanyinian.xyz/api/v1/client/subscribe?token=f64ab6f1d58f1120064b61da41e84f47
  - https://showdb.389123.xyz/s/7550a6896f04d30e7f195ea1a0569aec
  - https://www.s.aifjj.asia/api/v1/client/subscribe?token=3eddd42e9dc1e77d881326ad87da9246
  - https://su1b.suzu.shop/link/d2dYfrljZfDDUoF1?sub=3
  - https://cyberguard.cfd/api/v1/client/subscribe?token=221cae531c12b6ab93c5b223d7513ff0
  - https://cyberguard.cfd/api/v1/client/subscribe?token=65526ef654bb0f2e4b6a4163164bf05a
  - https://cyberguard.cfd/api/v1/client/subscribe?token=94cfa51eaf3e9b97fbe01928f7ca909e
  - https://fs.v2rayse.com/share/20250825/vg8r8ftdyx.yaml
  # TG #
  # 小汐搬运
  - 
  - 
  - 
  - 
  - 
  - 
  - https://banyunxiaoxi.icu/2025/09/14/2025-09-14%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0195%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/09/13/2025-09-13%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0191%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/09/12/2025-09-12%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0100%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/09/11/2025-09-11%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0120%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/09/10/2025-09-10%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0145%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/09/09/2025-09-09%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0173%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/09/08/2025-09-08%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B093%E4%B8%AA/
  # 白嫖免费节点：@zhibeii @juzibaipiao
  - 
  - 
  - 
  - 
  - https://neko-warp.nloli.xyz
  - https://sub.cm/iFRGOmJ
  - http://1i8.cn/nwdtl
  - https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3QvcyFBcWNyX0lvTkZNV0FlX21WLWxnMkRiclhvNHM_ZT1MZVI4Ym8
  - 
  - 
  - https://tt.vg/OHUJQ
  - https://v1.mk/GWyQjkD
  - https://tt.vg/BHZgL
  - https://v1.mk/krarqKk
  - https://v1.mk/lnJHPV0
  - https://tt.vg/XcHTN
  - https://v1.mk/Eeg53Jf
  - https://v1.mk/T6wJHIv
  - https://igdux.top/YkpZ
  - https://v1.mk/QnlNxlN
  - https://cache.ravelloh.top?uuid=f3d5c774-62ea-c52d-5b22-a7c44a663150
  - https://igdux.top/i2f2
  # 蛋黄酱节点分享：@FProxies
  # 0801节点
  - https://sub.danhu.ddns-ip.net/paste/B250901NyrjIGqKc/clash
  - https://sub.danhu.ddns-ip.net/paste/B250901NyrjIGqKc/urls
  # 轩辕节点永久订阅：@fq521
  - https://xyfqzy.zone.id/yyds/auto
  - https://svip.xy666.ggff.net/auto
  - https://ghfast.top/https://raw.githubusercontent.com/xyfqzy/free-nodes/refs/heads/main/nodes/clash.yaml
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/
  - https://proxypool.dmit.dpdns.org/clash/proxies
  - https://rss.zyfx6.xyz/v2rayNG/
  # 总节点保存
  - https://ghfast.top/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/youtube.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/speed.yaml
  # Github共享节点
  - https://ghfast.top/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://ghfast.top/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghfast.top/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.txt
  # 备用节点
  - https://ghfast.top/https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/v2ray.txt
  - https://ghfast.top/https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt
  - https://ghfast.top/https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt
  - https://ghfast.top/https://raw.githubusercontent.com/snakem982/proxypool/main/source/v2ray-2.txt
  - https://ghfast.top/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list_raw.txt
  - https://ghfast.top/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghfast.top/https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/free-nodes/v2rayfree/refs/heads/main/v1
  - https://ghfast.top/https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list_raw.txt
  - https://ghfast.top/https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/proxies.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
  - https://ghfast.top/https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml