# 是否打印进度
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 120
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://www.youtube.com/generate_204
  # alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 9999
  # 下载测试超时时间 单位秒
  download-timeout: 2
  # 测速下载大小 单位MB
  download-size: 10
  # 测速地址
  speed-test-url:
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  speed-skip-name: (IN|DE|NL|VN|UN|AU|AE|BR|TR|x\d+(\.\d+)?|\d+(\.\d+)?x)
  # 测速并发
  speed-check-concurrent: 5
  # 测速数量
  speed-count: 10
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  - https://s1.byte11.com/api/v1/client/subscribe?token=1946f1ba6dc724c79cbe3f2c2c41336a
  - https://paste.c-net.org/MalakaiBobka
  - 
  - 
  - 
  - 
  - https://ktm.zuuqb.cn/api/v1/client/subscribe?token=e2a19321bb8564a6f004c821933d0a04
  - https://dash.pqjc.site/api/v1/client/subscribe?token=0f70c1deaeab84ba25c825d2709ebfe4
  - https://sfj.sufujia.top/api/v1/client/subscribe?token=14ab155324e4b402c63df1a69711d779
  - https://xmrhuman.644222.xyz:8081/hui/VhFoUYo63Hx.s3vKndrp%2AxJ
  - https://wanmeiwl1.xyz/gywl/d58aeba1b86bacdc22e6a1856aca0f4d
  - https://anek0.no-mad-world.club/link/eLZUdlb5HXpA63EE?clash=3&extend=1
  - https://pianyi.wangpankehuduan.homes/answer/land?token=dab648f085e6d42108f8ad399b62e304
  - https://igdux.top/XSGiKjiRmASeDYFiDaB3rFdX
  - https://fg88.whtjdasha.com/api/v1/client/subscribe?token=7bbd0dbe02bcebb1b94e2cdf7c27770c
  - https://gogof.hgfastgo.com/api/v1/client/subscribe?token=fdcb29a03a96c3296620ef37d7f9a890
  # TG #

  # 小汐搬运
  - 
  - 
  - https://banyunxiaoxi.icu/2025/10/06/2025-10-06%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0230%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/10/05/2025-10-05%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0212%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/10/04/2025-10-04%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0207%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/10/03/2025-10-03%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0218%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/10/02/2025-10-02%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0216%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/10/01/2025-10-01%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0256%E4%B8%AA/

  # 白嫖免费节点：@zhibeii @juzibaipiao
  - 
  - 
  - https://v1.mk/aQtRr1t
  - https://igdux.top/zkFx
  - https://igdux.top/h7Zk
  - https://igdux.top/ASB6
  - https://igdux.top/eJBd
  - https://v1.mk/RusSGkY
  - https://tt.vg/tiySV
  - https://tt.vg/cBWKh
  - https://tt.vg/qrLAw
  - https://tt.vg/AoJZj
  - https://tt.vg/WqAfE
  - https://tt.vg/wRypr
  - https://tt.vg/IHZnp
  - https://tt.vg/ecsIA
  - https://tt.vg/kXahx
  - https://tt.vg/MhDOv
  - https://v1.mk/U2CW63F
  - https://v1.mk/YCs6ZzQ
  - https://v1.mk/DWNmjLL
  - https://v1.mk/fHn34KA
  - https://v1.mk/dreNmVT
  - https://v1.mk/sLwkCDQ

  # 蛋黄酱节点分享：@FProxies
  # 0920节点
  - https://sub.danhu.ddns-ip.net/paste/B250920NXFUDdV0a/clash
  - https://sub.danhu.ddns-ip.net/paste/B250920NXFUDdV0a/urls
  # 1001节点
  - https://sub.danhu.ddns-ip.net/paste/A251001N1rhoxeHA/clash
  - https://sub.danhu.ddns-ip.net/paste/A251001N1rhoxeHA/urls
  # 轩辕节点永久订阅：@fq521
  - https://xyfqzy.zone.id/yyds/auto
  - https://ghfast.top/https://raw.githubusercontent.com/xyfqzy/free-nodes/refs/heads/main/nodes/clash.yaml
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/
  - https://proxypool.dmit.dpdns.org/clash/proxies
  - https://rss.zyfx6.xyz/v2rayNG/
  # 白嫖のHome：@ZDYZ2
  - https://sublink.634676.xyz/sub
  # 总节点保存
  - https://ghfast.top/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/youtube.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/speed.yaml
  # Github共享节点
  - https://ghfast.top/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://ghfast.top/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghfast.top/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.txt
  # 备用节点
  - https://ghfast.top/https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/v2ray.txt
  - https://ghfast.top/https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt
  - https://ghfast.top/https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt
  - https://ghfast.top/https://raw.githubusercontent.com/snakem982/proxypool/main/source/v2ray-2.txt
  - https://ghfast.top/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list_raw.txt
  - https://ghfast.top/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghfast.top/https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/free-nodes/v2rayfree/refs/heads/main/v1
  - https://ghfast.top/https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list_raw.txt
  - https://ghfast.top/https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/proxies.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub
  - https://ghfast.top/https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml