# 是否打印进度
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 30
  # 检查间隔,单位分钟
  interval: 120
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://www.youtube.com/generate_204
  # alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 1500
  # 最低测速 单位KB/s
  min-speed: 9999
  # 下载测试超时时间 单位秒
  download-timeout: 3
  # 测速下载大小 单位MB
  download-size: 30
  # 测速地址
  speed-test-url:
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 6
  # 测速数量
  speed-count: 14
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  - https://banyunxiaoxi.icu/2025/06/18/2025-06-18%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0152%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/06/19/2025-06-19%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0153%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/06/17/2025-06-17%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0142%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/06/17/2025-06-17%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0139%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/06/14/2025-06-14%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0118%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/06/20/2025-06-20%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0140%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/06/23/2025-06-23%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0136%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/06/24/2025-06-24%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0176%E4%B8%AA/
  - 
  - 
  - 
  - 
  - 
  - 
  - https://v1.mk/xzkZaXt
  - https://www.vns735p8.xyz/api/v1/client/subscribe?token=cf734613f8dc3ca00cf2a690a5c54b58&connection=relay
  - https://v1.mk/a992uxW
  - https://v1.mk/87n2H5t
  - https://subapi.v1.mk/remoteconfig/2025/06/0621/59247e590462d689f01a511592b6eb99.ini
  - https://subapi.v1.mk/remoteconfig/2025/06/0621/3b901b7d03cb7cde3a545d8d4cdd04ad.ini
  - https://tt.vg/pqacC
  - https://img.xn--mesv8bx6xmtl.com/static/0da90e055ceb1751e21527c27d1e6c86
  - https://aecc-dfghjkk.kaell.top/api/v1/client/subscribe?token=3891fe6c14bb296429886c4f10bb80bf
  - http://admin.vip.edu.kg/s/ed253470c66f9c2a2da0b694e087e1ef
  - https://subapi.v1.mk/remoteconfig/2025/06/0620/156bd7bdf33a7640401557203d818494.ini
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1
  - https://awa.inekokkk.immobilien/amei/8aa558d7f035fe9b3a2bcd3a0f6d4482
  - https://xb.inekokkk.com/amei/5fdef0617edecedfda805ddf3e8a320d
  - https://xb.inekokkk.com/amei/5b795ddfa7ff56965b82ca09bcde8b1d
  - https://xb.inekokkk.com/amei/6d753889b902220fcc9ebf6b38468b68
  - https://xb.inekokkk.com/amei/5aa3e66694750fe269c0efef4bad4b07
  - https://xb.inekokkk.com/amei/0c230a6f6a95c9a9d3cdada708c9b1cb
  - https://xb.inekokkk.com/amei/a7826885f196a1d611929641072de890
  - https://xb.inekokkk.com/amei/8da06b49f1e3bfbf7adc0e4657c2a7ea
  - https://xb.inekokkk.com/amei/b9e41797cf434b1aa09921c36386d471
  - https://awa.inekokkk.immobilien/amei/3373fbca49736e8990c6e47e49157ba4
  - https://xb.inekokkk.com/amei/54194127b8bc20294f3fc8e96e3a2c66
  - https://awa.inekokkk.immobilien/amei/8aa558d7f035fe9b3a2bcd3a0f6d4482
  - https://xb.inekokkk.com/amei/5fdef0617edecedfda805ddf3e8a320d
  - https://xb.inekokkk.com/amei/5b795ddfa7ff56965b82ca09bcde8b1d
  - https://xb.inekokkk.com/amei/6d753889b902220fcc9ebf6b38468b68
  - https://xb.inekokkk.com/amei/5aa3e66694750fe269c0efef4bad4b07
  - https://xb.inekokkk.com/amei/0c230a6f6a95c9a9d3cdada708c9b1cb
  - https://xb.inekokkk.com/amei/a7826885f196a1d611929641072de890
  - https://xb.inekokkk.com/amei/8da06b49f1e3bfbf7adc0e4657c2a7ea
  - https://xb.inekokkk.com/amei/b9e41797cf434b1aa09921c36386d471
  - https://ooooooo.vvvv.ee/O
  - https://kkkkkkk.vvvv.ee/K
  - https://xb.inekokkk.com/amei/6d753889b902220fcc9ebf6b38468b68
  - https://sub.xn--vpn-3f0h822m.com/s/120736a78227400ace8535d3bbcbcff1
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1&flag=meta
  - https://v1.mk/0lxePC7
  - https://dyzk.020318.xyz/?token=d24404a213fc4dd681536826c509e0a1&flag=meta
  - http://99.83.189.142:53826/sub/e38847ba902308ea/clash/%E6%9E%81%E9%80%9FVPN
  - https://v1.mk/3sJEIIf
  - https://ylks.tt2000.sbs/2025/F4/x18/c.yaml
  - https://v1.mk/jFKrtal
  - https://tt.vg/ljcmv
  - https://tt.vg/AgNbe
  - https://fly0001.buzz/gateway/feitu?token=af2b7c2e52fd794814c6f2ea7a06120e
  - https://sub.xn--mes358awwugpa.com/sub?token=552d8dc592e368f9438dff0061c1d9fe
  - https://ylks.tt2000.sbs/2025/F4/s17/c.yaml
  - https://v1.mk/kqGNjdR
  - https://tt.vg/ctZhP
  - https://v1.mk/d4FZgN3
  - https://ylks.tt2000.sbs/2025/F4/u16/c.yaml
  - https://v1.mk/RlOi4xX
  - https://v1.mk/u81zQBi
  - https://admin.shanlian.app/api/v1/client/subscribe?token=LeuTD8BJwlJ9G5PFv7y3pXdzCshI4Dma
  - https://premiumeconomy.carpetpacific.com/y7xxdjec4y/b1anket/zhb4ixhmtm/api/v1/client/subscribe?token=a673c45df715365fc28f7293d308cbc8
  - https://vpn.huasuan666.top/api/v1/client/subscribe?token=c384811f63c704a7cd6e98a6c87f79fc
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=47b575570f529022d5778582572db59e
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=b10f75a290433b946d009600b05368a5
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=5810a6ae993d64cedc6f8ec5ebac043a
  - https://hs.huasuan666.top/api/v1/client/subscribe?token=02817e08b4676029b91d612843be9b1a
  - https://hs.huasuan666.top/api/v1/client/subscribe?token=39fd8e901d4da2b6c0bf56add49b4dca
  - https://vpn.huasuan666.top/api/v1/client/subscribe?token=ef8b67b92eb9927e21195397b3d04a03
  - https://jc.huasuan666.top/api/v1/client/subscribe?token=b10f75a290433b946d009600b05368a5
  - https://ylks.tt2000.sbs/2025/F4/v13/c.yaml
  - https://ylks.tt2000.sbs/2025/F4/11n/c.yaml
  - https://tc.qy1357.top/api/v1/client/subscribe?token=99843c5ab80547cfb0a55516f6b0d0e7
  - https://tt.vg/hhdEL
  - https://463036dc-5f99-4032-9f56-714073fa0e33.abyssvpn.xyz/Abyss/090ca312ced4dccd0f86cf76bf0e8b21
  - https://vip.subscribe-needay.xyz/api/v1/client/subscribe?token=a87d6b8525451894286843fa4eae592b
  - https://yyds.xueshan.shop/s/509f4c4224975aa87d8f96cb2d544f0c
  - https://x.juzi.lat/view.php?id=6b7c83420274dcdb
  - https://img.xn--mesv8bx6xmtl.com/static/c649455815ae4bc5087798983a740feb
  - https://img.xn--mesv8bx6xmtl.com/static/c649455815ae4bc5087798983a740feb
  - https://95.qy1357.top/api/v1/client/subscribe?token=b2b644a2ba32aada7dfb5859c59e36a3
  - https://getinfo.bigwatermelon.org/s?token=d6ffddb3abf6fcf9288dc26937156397
  - https://getinfo.bigwatermelon.org/s?token=70fd57dcf823931c4a6cd5909421711d
  - https://api.bppp.shop/api/sub/5f71bc8019b1d93ac6b0230a43f38840
  - https://api.bppp.shop/api/sub/921af3220df0280315f9c45c14622e6a
  - https://sub.xn--vpn-3f0h822m.com/s/6e90e56a54c401970721aff9f65bc7c9
  - https://sub.372372.xyz/api/v1/client/subscribe?token=024e356371111d8f84b0d93052868143
  - https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5
  - https://e.db01.in/link/7nOpKBwclgYbweua?clash=1
  - https://www.dabai.in/link/O4SwmMZ1eEaBoH1O?clash=1
  - https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5
  - https://sub.372372.xyz/api/v1/client/subscribe?token=024e356371111d8f84b0d93052868143
  - https://www.dabai.in/link/O4SwmMZ1eEaBoH1O?clash=1
  - https://dy11.baipiaoyes.com/api/v1/client/subscribe?token=5ff2c5ce71d1b68af9a39691adf71a64
  - https://api-bigbear-v2-sub.sodtool.com/subscribe/universal?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEzNTA4NTMsInVzZXJJZCI6ImRhMmQ3ZjUyZTFiMjQ2NDc4NTM1YmI3ODYyZDJjY2QwIn0.dp3QF6CeYaWm46Hc_LBg_bhKcjcP3GK5wGhISpcpFvI&device_type=
  - http://13.248.254.117/sub/295c1a32b309293c/clash/%E9%A3%9E%E9%B8%9F%E5%8A%A0%E9%80%9F?route=0
  - https://api.x5533.cn/api/v1/cliont/svbhghcribe?token=5ef2b17a1be6469e051d0f58f35c8b23
  - https://a.545437.xyz/jiji?token=e6131819bcf560b8f3e28180339efe44
  - https://nano.nachoneko.cn/api/v1/client/subscribe?token=76f11057c2731a948cc6d0ab9b9bd313
  - https://user7588.eyudy.one/api/v1/client/subscribe?token=64aef9e2b551b427214bf2e4b94d2d0b
  # TG #
  # 蛋黄酱节点分享：@FProxies
  # 0404节点
  - https://sub.danhu.ddns-ip.net/paste/5WuzWpeUGwpoaS4V/base64
  - https://sub.danhu.ddns-ip.net/paste/5WuzWpeUGwpoaS4V/clash
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto
  - https://svip.xy666.ggff.net/auto
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/
  # 总节点保存
  # Github共享节点
  - https://ghproxy.net/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.txt
  # 备用节点
  - https://ghproxy.net/https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Roywaller/clash_subscription/refs/heads/main/clash_subscription.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/clash/naidounode.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/mgit0001/test_clash/refs/heads/main/heima.txt
  - https://ghproxy.net/https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/README.md
  - https://ghproxy.net/https://raw.githubusercontent.com/Pawdroid/Free-servers/refs/heads/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/shahidbhutta/Clash/refs/heads/main/Router
  - https://ghproxy.net/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml