# 是否打印进度 
print-progress: true

# 可选值 debug info warn error
log-level: info

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 10
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 2048
  # 下载测试超时时间 单位秒
  download-timeout: 4
  # 测速下载大小 单位MB
  download-size: 20
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  #speed-skip-name: 倍率|x\d+
  # 测速并发
  speed-check-concurrent: 2
  # 测速数量
  speed-count: 20
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  # 临时节点
  # - 
  # - 
  # - 
  # - 
  - https://book.hostnow.top/api/v1/client/subscribe?token=e1a90ec2dfd92a6a8f75b3b224ecfbaa
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=3c9b4a6988f77f7631e07dae2aa9721b
  - https://igdux.top/TwcchR34f7dGeH4Hza6nyfWF
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=531e0be2dbbfc393dfac550abee6ce57
  - https://paste.ee/d/R3fZLg5J
  - https://fsc.jiediandingyuejiji.homes/answer/land?token=ebf77cdb420eb8bd6ccc30564d9bd588
  - https://xn--mesz9ptugxg.com/api/v1/client/subscribe?token=dcb2eb6379a152bbe397572220e8e4a8
  - https://v1.mk/7IkXyiR
  - https://v1.mk/BxTdHqC
  - https://prjcm.itr.lol/link/VIP/ofoNET?token=138790b1ab408e30b1fff9e4e0d114a4
  - https://s1.byte16.com/api/v1/client/subscribe?token=ffc05e97d39d2efbdba15693857014a0
  - https://v2.ixlmo.net/api/v1/client/subscribe?token=67bc22d07a835ee03f143878b7f6199d
  - https://sub.verybigball.org/download-sub/?sid=151788&uid=3760&token=64e0e48a77343e4971fb&app=auto
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c0d689384b0f7f0362940e126b7a4a63
  - https://sub.nexc.cc/api/v1/client/subscribe?token=6653dae74bb2813201976ce8561b37c8
  - https://sub.nexc.cc/api/v1/client/subscribe?token=8ed3fe4c475e3f339dbf760ae72667df
  - https://s1.byte33.com/api/v1/client/subscribe?token=864188658b08e49f16ced2969513e47c
  - https://g15311cec.cdn.uunode.com/apiv2/user/sub?token=7fb4e06fd96e39cedd21e8ff66b00d48
  - https://xqsub.e54.site/api/v1/client/subscribe?token=df86b7f78767c9dbc46e447d74d60097
  - https://xqsub.e54.site/api/v1/client/subscribe?token=df46d6a227769469523c2eb2c8d5b5ee
  - https://xqsub.e54.site/api/v1/client/subscribe?token=0f535ce035f582453bf47bfd027b0243
  - https://xqsub.e54.site/api/v1/client/subscribe?token=13f94a3c83abb2a248e46dd37621f9de
  - https://xqsub.e54.site/api/v1/client/subscribe?token=519170be32226978a75ebc9ec38813dd
  - https://xqsub.e54.site/api/v1/client/subscribe?token=144b17a92ca77c9bc3c55e173d33c41a
  - https://xqsub.e54.site/api/v1/client/subscribe?token=f6f20d728dc4dc7307572fee8116b08d
  - https://xqsub.e54.site/api/v1/client/subscribe?token=27b0079c3c0c3f06630c42074a62be19
  - https://xqsub.e54.site/api/v1/client/subscribe?token=b9669d7ce0265a9be4265ae5a9d22d57
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c995b9ab2b53f2f49b80bb1273472b93
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c0d689384b0f7f0362940e126b7a4a63#/0元白嫖机场，注册不验证
  - https://xqsub.e54.site/api/v1/client/subscribe?token=a324065263835ed0a596d96872c3886f
  - https://xqsub.e54.site/api/v1/client/subscribe?token=78406b68ace9653c493709dafde1634c
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=531e0be2dbbfc393dfac550abee6ce57#用光自动补满
  - https://amvne.ofourl.xyz/link/VIP/ofoNET?token=7c47f0c1cb8acbc8b0470c4bff4a284c
  - https://g871cec.cdn.uunode.com/apiv2/user/sub?token=bebf85760972ff4b242529642eb36efb
  - http://nuxyun.v2rayflash.top/api/v1/client/subscribe?token=531e0be2dbbfc393dfac550abee6ce57
  - https://xboard.zszweb.pp.ua/api/v1/client/subscribe?token=7b1c94e78a2852d0d9e4766b1d1e61b9
  - https://pianyi.sub.sub.subsub123456789.com/answer/land?token=6764d0eab8283058a5521054fd09c1d5
  - https://pianyi.sub.sub.subsub123456789.com/answer/land?token=bbb3a9f81235c1d763cad3cae8188be5
  - https://ly.ccwink.cc/api/v1/client/subscribe?token=85ce9c6ba278c9f8e194bb98087382f0
  - https://fsc.jiediandingyuejiji.homes/answer/land?token=ebf77cdb420eb8bd6ccc30564d9bd588
  - https://sub.nexc.cc/api/v1/client/subscribe?token=8ed3fe4c475e3f339dbf760ae72667df
  - https://sub.nexc.cc/api/v1/client/subscribe?token=6653dae74bb2813201976ce8561b37c8
  - https://sub.verybigball.org/download-sub/?sid=151788&uid=3760&token=64e0e48a77343e4971fb&app=auto
  - https://sub.verybigball.org/download-sub/?sid=151783&uid=3752&token=c1f2ecf5ee4127d2d10b&app=auto
  - https://s.yyzzyyds.xyz/yyzz/114514/subscribe/c8ef81b8c2d18c41b276bc0a7cf4c1ec
  - https://s.yyzzyyds.xyz/yyzz/114514/subscribe/7c0c89371d3a43136028aff8a7b43f9e
  - https://xqsub.e54.site/api/v1/client/subscribe?token=f6f20d728dc4dc7307572fee8116b08d
  - https://xqsub.e54.site/api/v1/client/subscribe?token=b9669d7ce0265a9be4265ae5a9d22d57
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c995b9ab2b53f2f49b80bb1273472b93
  - https://xqsub.e54.site/api/v1/client/subscribe?token=144b17a92ca77c9bc3c55e173d33c41a
  - https://xqsub.e54.site/api/v1/client/subscribe?token=27b0079c3c0c3f06630c42074a62be19
  - https://xqsub.e54.site/api/v1/client/subscribe?token=c0d689384b0f7f0362940e126b7a4a63
  - http://em7.buzz/v3/subscr?id=d5363e1171244baab0a1dbd5ac69630c
  # 总节点保存
  - https://ghproxy.net/https://raw.githubusercontent.com/mitjavaz/memo/master/allNodes.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://ghproxy.net/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghproxy.net/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://ghproxy.net/https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghproxy.net/https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://ghproxy.net/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  # TG #
  # 蛋黄酱节点分享：@FProxies
    # 0208节点
  - https://sub.danhu.ddns-ip.net/paste/OmJ9zWdyc6ZN9aAe/clash
  # 轩辕节点永久订阅：@fq521
  - https://vip.xy666.ggff.net/auto