# 是否打印进度
print-progress: true

# 可选值 debug info warn error
log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: mix
  flag: true

check:
  # 并发
  concurrent: 20
  # 检查间隔,单位分钟
  interval: 120
  # 测试节点存活的url 默认 https://gstatic.com/generate_204
  alive-test-url: https://www.youtube.com/generate_204
  # alive-test-url: https://gstatic.com/generate_204
  # 判断节点存活的状态码 默认 204
  alive-test-expect-code: 204
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 9999
  # 下载测试超时时间 单位秒
  download-timeout: 4
  # 测速下载大小 单位MB
  download-size: 40
  # 测速地址
  speed-test-url:
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  speed-skip-name: 
  # 测速并发
  speed-check-concurrent: 5
  # 测速数量
  speed-count: 14
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    #- openai
    - youtube
    #- netflix
    #- disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: ["local"]
  # 保存端口
  #port: 18989

# mihomo api
#mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
#mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 1
# 代理设置 支持 http 和 socks 代理
proxy:
#  type: "http" # 可选值: http, socks
#  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - https://x.juzi.lat/view.php?id=6febd11e9756e058
  - http://9uc.buzz/v3/subscr?id=952797b621a04e66923930ef5c0efcdf
  - https://banyunxiaoxi.icu/2025/07/30/2025-07-30%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0416%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/07/29/2025-07-29%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0516%E4%B8%AA/
  - https://banyunxiaoxi.icu/2025/07/28/2025-07-28%E8%8A%82%E7%82%B9%E6%9B%B4%E6%96%B0521%E4%B8%AA/
  - https://clck.ru/3MjhBu
  - https://xtls.rprx.vision/api/v1/client/subscribe?token=a49c8d24c16f8295952c716fdbaa4280
  - https://slimy-janine-lirtpass-0136632c.koyeb.app/share/file/dingyue_Center_post0726?token=g0X6qoKeORSfXmqhTfy9s
  - http://8.138.34.87:3389/saccess/e7d0d3eaf818aedff31df8ed802fffa0
  - https://api-bigbear-v2-sub.sodtool.com/subscribe/universal?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEzNTA4NTMsInVzZXJJZCI6ImRhMmQ3ZjUyZTFiMjQ2NDc4NTM1YmI3ODYyZDJjY2QwIn0.dp3QF6CeYaWm46Hc_LBg_bhKcjcP3GK5wGhISpcpFvI&device_type=
  - https://api.x5533.cn/api/v1/cliont/svbhghcribe?token=5ef2b17a1be6469e051d0f58f35c8b23
  # TG #
  # 白嫖免费节点：@zhibeii
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - https://v1.mk/ZSbMn7s
  - https://v1.mk/CarE3tp
  - https://v1.mk/df0oVBg
  - https://v1.mk/IXxDHKZ
  - https://v1.mk/kbUCs70
  - https://v1.mk/vcShNug
  - https://v1.mk/qob6Tbx
  - https://v1.mk/MG6a7oL
  - https://v1.mk/m6ytabR
  # 蛋黄酱节点分享：@FProxies
  # 0801节点
  - https://sub.danhu.ddns-ip.net/paste/B250801N3NYIThkB/base64
  - https://sub.danhu.ddns-ip.net/paste/B250801N3NYIThkB/clash
  - https://sub.danhu.ddns-ip.net/paste/B250801N3NYIThkB/urls
  # 轩辕节点永久订阅：@fq521
  - https://ghfast.top/https://raw.githubusercontent.com/xyfqzy/free-nodes/refs/heads/main/nodes/clash.yaml
  # 资源分享：@txwl666
  - https://rss.zyfx6.xyz/clash/
  - https://rss.zyfx6.xyz/v2rayNG/
  # 总节点保存
  - https://ghfast.top/https://raw.githubusercontent.com/mitjavaz/memo/master/BestSub/output/all.yaml
  # Github共享节点
  - https://ghfast.top/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt
  - https://ghfast.top/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghfast.top/https://raw.githubusercontent.com/hkaa0/permalink/main/proxy/clash.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/freeVPNjd/freeVPN1/main/clash
  - https://ghfast.top/https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/resasanian/Mirza/main/sub
  - https://ghfast.top/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghfast.top/https://raw.githubusercontent.com/ZywChannel/free/main/sub
  - https://ghfast.top/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/list.txt
  # 备用节点
  - https://ghfast.top/https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Roywaller/clash_subscription/refs/heads/main/clash_subscription.txt
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc0.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc1.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc2.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc3.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Q3dlaXpoaQ/V2rayN_Clash_Node_Getter/refs/heads/main/APIs/sc4.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/xiaoji235/airport-free/refs/heads/main/clash/naidounode.txt
  - https://ghfast.top/https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml
  - https://ghfast.top/https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/snakem982/proxypool/main/source/clash-meta.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml
  - https://ghfast.top/https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
  - https://ghfast.top/https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/mgit0001/test_clash/refs/heads/main/heima.txt
  - https://ghfast.top/https://raw.githubusercontent.com/aiboboxx/v2rayfree/refs/heads/main/README.md
  - https://ghfast.top/https://raw.githubusercontent.com/shahidbhutta/Clash/refs/heads/main/Router
  - https://ghfast.top/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml
  - https://ghfast.top/https://raw.githubusercontent.com/anaer/Sub/refs/heads/main/clash.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml
  - https://ghfast.top/https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml
  - https://ghfast.top/https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
  - https://ghfast.top/https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml